Kommunicate-io/Kommunicate-Web-SDK

- webplugin/build/test.txt
-> In Windows machine if someone freshly clones the repo and try to run the server using `node app` then node throws the following error **`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory`**. This error arises because the project is unable to create a `build` folder in the `webplugin` directory. To avoid this error we can create an empty build folder in the `webplugin` directory. And we've already added the `build` folder exception in the `.gitignore` file.
> Creating build folder in Web Plugin folder to avoid error in Windows

- .gitignore
- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
-> Fix `Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.` error when cookies are disabled.
1. Disable Cookies in the browser and load sidebox script.
2. Sidebox will load with no error in console.
3. A conversation will be created automatically on click of chat launcher and messages will be sent and received smoothly.
-> Type of `undefined` will not work in case of `sessionStorage` and `localStorage` if Cookies are disabled.
-> If cookies are blocked in the browser then our sidebox widget will not load as it is dependent on both Session Storage and Local Storage of the browse. And if cookies are disabled then both Session Storage and Local Storage will be inaccessible by the window object. 
NOTE: Make sure you're …
> [WIP] CO-513 Cookies and SessionStorage Error Fix [WIP]

- webplugin/js/app/mck-app.js
-> Load all external script together
-> Don't let Kommunicate JS files load before external scripts are loaded.
-> By running Kommunicate script on slow connections and by clearing all browsing data (including cache)
-> All JS files other than jquery were loading parallelly which was sometimes loading Applozic minified file after our Kommunicate file which was the root cause of this error.
> CO-544 Load all external script together and don't let kommunicate JS files load before external scripts are loaded.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
-> Whenever the current browser tab in which the script is running, is not in focus and a new message arrives then the current browser tab's title will say **`New message from <Sender Name>`**.
-> By setting `messageTriggerTimeout` in `appOptions` and switching to different tab after reloading the tab with the script running.
-> By sending the message from the dashboard when the current tab is not in focus and widget is closed.
-> https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
-> Fixed an issue where the chats not auto-scrolling when a new message arrives or when the user sends a message. This issue is already fixed and merged in release branch by @akshatdhabi but was not merged in master.
> CO-272 New message indicator in document's title

- webplugin/js/app/mck-app.js
-> Chat widget should start using new userId after a certain amount of session timeout.
Step-1 Performed fresh login using Kommunicate install script.
Step-2 Refresh the page it will open same chat thread until the session timeout limit reaches.
Step-3 Once the session timeout limit reaches it will start the widget using new userId.
> CO-567 Session timeout for chat widget.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-app.js
-> Changed CDN URL of jQuery file from `ajax.googleapis.com` to `cdnjs.cloudflare.com` to add support for China users.
-> Fixed an issue where the chat launcher icon was scrolling out of view in Android devices with Chrome version 75 while scrolling. This is an issue with the latest version of Chrome on Android. I've filed a bug on `bugs.chromium.org` and they've given a temporary workaround while they are fixing this issue and releasing it in next version. 
> Fix China CDN issue and launcher scrolling out of view issue [RELEASE]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-app.js
-> Changed CDN URL of jQuery file from `ajax.googleapis.com` to `cdnjs.cloudflare.com` to add support for China users.
-> Fixed an issue where the chat launcher icon was scrolling out of view in Android devices with Chrome version 75 while scrolling. This is an issue with the latest version of Chrome on Android. I've filed a bug on `bugs.chromium.org` and they've given a temporary workaround while they are fixing this issue and releasing it in next version. 
> Fix China CDN issue and launcher scrolling out of view issue [MASTER]

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/pluginOptimizer.js
- webplugin/template/mck-sidebox.html
-> Remove commented links inside HTML file.
-> Replace jquery code inside mck-app.js with JS.
-> Fixed bug where C-SAT rating was showing in the wrong thread.
-> Added sessionTimeout support in appOptions(preference will be given to appOptions if sessionTimeout is coming from application settings API).
-> Removed Twilio related reference from the mck-app.js file.
-> **sessionTimeout**
Bypassing sessionTimeout : <integer value in milliseconds> in install script.
-> **C-SAT rating**
By first opening two threads 1 and 2, then opened thread 2 and resolving thread 1 from the dashboard.
-> **Jquery->JS**
By creating new build and checking that everything is working fine in our Sidebox.
-> For the real-time update of C-SAT rating the check was added inside onMessage function to detect the …
> C-SAT bug fix, support for sessionTimeout via appOptions and replaced Jquery with JS.

- webplugin/js/app/kommunicate-client.js
-> Added `userLocale` option in appOption to set the language of the welcome messages. If this option is not available in appOption then the browser language will be set as the language of the welcome messages.
-> Sending `"{"kmUserLocale":"en"}"` in `KM_CHAT_CONTEXT` of the group metadata to set the welcome language of the user.
-> By adding `userLocale: "en-US` in appOption. 
->
->
> CO-457 added appOption in install script to set user locale 

- webplugin/js/app/mck-sidebox-1.0.js
-> TypeError: null is not an object (evaluating 'o.ctx.createGain') is thorwing on Safari sometimes. due to this error plugin is not loading.
https://github.com/goldfire/howler.js/issues/1021
the plugin should load if any error throw from howler library
-> created a sample webpage and loaded plugin multiple times on different tabs using the link button 
->
->
> catch error from howler

- webplugin/js/app/mck-sidebox-1.0.js
-> Fixed an issue whenever any agent was sending a message from the dashboard to the user on the chat widget then the image that was showing on the popup widget was of the assignee of that conversation and not the one of the agent that sent that message.
-> The code was tested by sending the messages to the chat widget where the widget is minimized (closed).
-> Also tested by sending the messages from those agents who are not part of the conversation initially but later added in the conversation.
> CO-636 Incorrect photo coming in notification popup for messages sent from dashboard

- webplugin/js/app/mck-sidebox-1.0.js
-> Adding `alt` attribute in image `<img>` tag so that when navigating screenreaders should read the name of the image from the alt tag and not the image URL itself.
-> By running NVDA and navigating through the chat widget.
->
->
> CO-581 adding alt tags in profile image of agent in sidebox for accessibility

- webplugin/js/app/mck-sidebox-1.0.js
-> Fixed a bug where `https://api.kommunicate.io/img/logo02.svg` this url was giving 404 error so replaced it with `https://cdn.kommunicate.io/kommunicate/bot_default_image.png` this one.
> Updated image url for bot whose default image is not present

- .vscode/settings.json
- webplugin/css/app/mck-sidebox-1.0.css
-> By sending bot's rich message in the chat with the widget is closed.
-> Fixed a bug where the Rich Message icon in the popup message notification was being cut in half when a rich message arrives from bot in chat as seen in the screenshot below.
> Fix Rich Message Icon visual bug in popup message notification

- webplugin/css/app/mck-sidebox-1.0.css
-> By sending bot's rich message in the chat with the widget is closed.
-> Fixed a bug where the Rich Message icon in the popup message notification was being cut in half when a rich message arrives from bot in chat as seen in the screenshot below.
> Fix Rich Message Icon visual bug in popup message notification [MASTER]

- webplugin/css/app/mck-sidebox-1.0.css
-> By sending bot's rich message in the chat with the widget is closed.
-> Fixed a bug where the Rich Message icon in the popup message notification was being cut in half when a rich message arrives from bot in chat as seen in the screenshot below.
> Fix Rich Message Icon visual bug in popup message notification [RELEASE]

- webplugin/css/app/mck-sidebox-1.0.css
-> By sending a message from the dashboard to the chat widget while the chat widget is closed.
-> Screenshots:
> CO-791 fixed images with ratio other than 1:1 getting cut in launcher icon

- webplugin/js/app/mck-sidebox-1.0.js
- prevent the group create call to go multiple times incase user enters 
```
KommunicateGlobal.document.getElementById('mck-sidebox-launcher').addEventListener('click',function(e){
Kommunicate.startConversation();
});
```
- also stopped the click event on sidebox launcher being called twice
- code was tested in my local environment for cases mentioned above.
> prevent group create call from going multiple times

- webplugin/js/app/events/applozic-event-handler.js
- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- Set the default group name using startConversation method.
- Don't change conversation header on change of assignee in case if KM_ORIGINAL_TITLE is passed while group creation.
- Fix bug openConversationOnNewMessage of undefined.
- Calling below function in onInit Callback function 
Kommunicate.startConversation({
"defaultGroupName": "Github Commit",
}, function (response) {
console.log(response);
});
> CO-795  Set default group name using startConversation method.

- webplugin/js/app/mck-app.js
-> Fixed a bug where if the chat widget is loaded without any custom launcher icon then the chat widget launcher icon was visible.
The reason to add an `else` condition is to check if there is a custom launcher icon present or not. If it is not present then go through the `setInterval` and remove the `n-vis` class and add the animation class to show the smooth transition of the chat widget is visible in the webpage.
> CO-708 fix launcher with no custom image not visible

- webplugin/js/app/mck-sidebox-1.0.js
-> Removed check to get `botMessageDelayInterval` value from appOption in the install script, instead it will now be fetched from the appSettings API with same parameter name inside `chatWidget` object.
-> By setting `"botMessageDelayInterval": 2000` in the `chatWidget` object in App Settings API.
> CO-775 Bot message delay timer value will now be fetched from appSettings API

- webplugin/js/app/mck-sidebox-1.0.js
->
-> Fill detials in lead collection popup then reload the page now the pre chat popup notification will be visible.
->
->
> Making pre chat popup visible after the lead collection template is closed on second reload

- webplugin/js/app/km-rich-text-event-handler.js
-> on click of link button arrow icon, it should redirect to the link
-> on click of link button arrow icon, it is redirecting to the link
-> To get the data attribute of parent element even if the child element is clicked, use event. currentTarget instead of event. target
->
> TD-258: fix: on click of link button arrow icon, not redirecting to the link

- webplugin/js/app/mck-sidebox-1.0.js
-> Not allow the socket to make a message list call when it's getting initialized.
-> By adding the below code in Kommunicate script.
onInit: function (response, data) {
Kommunicate.launchConversation();
}
-> Whenever the socket was getting connected, we were making a message list call. So now when the socket connection will be initialized for the first time, we will avoid this call.
> Not allow socket to make message list call when it's getting initialized.

- webplugin/js/app/mck-app.js
-> By running the KM Script in IE and then reloading the page.
-> Fixed a bug where popup confirmation dialog was visible in IE11 whenever the user is reloading the page or navigating to some other section of the page where the KM Script is Installed.
> Fixed popup dialog visible in IE11 when closing tab

- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
-> Pre-chat popup widget will now work with Pre-chat lead collection.
-> By enabling pre-chat popup and adding pre-chat lead collection code inside `onInit: function() { ... }` in kommunicate install script.
> CO-841 Pre-chat popup will now work with pre-chat lead collection

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-ui.js
-> By loading sidebox script in the browser in the responsive mode.
-> Fixed a bug where the pre-chat popup message was being cut in mobile devices with width of less than 420 px.
-> Fixed issues with the width adjustment of the conversation title on the mobile devices with width of less than 420px.
Pre-chat popup
Conversation Title
Pre-chat popup
Conversation Title
> CO-829 Fix title width adjustment and pre-chat popup widget issues in mobile devices

- webplugin/js/app/media/media-dom-event-listener.js
-> Fix voice input not working.
-> Error came due to the concatenation of all multiple JS files to a single one.
The event listener was not getting attached because the JS file is adding the HTML to the dom. So the code was getting executed before the element was present in the DOM.
> Fix voice input not working.

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
-> When `isSingleThreaded` parameter is passed in the `chatWidget` object inside appSettings API then the back button and start new conversation button will be hidden.
-> By passing `true` and `false` value in the `isSingleThreaded` parameter in appSettings API.
> CO-855 Added Single Threaded Conversation in chat widget

- webplugin/css/app/km-rich-message.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
-> Added close button to close the pre-chat popup template as shown in the screenshot.
> - By enabling the pre-chat popup from the dashboard.
> - By hovering over the pre-chat popup template when it is visible on the widget to see the close button.
> - By clicking the close button of the pre-chat popup template to dismiss it.
> CO-852 Added close button in pre-chat popup template

- webplugin/js/app/mck-app.js
> - Remove session data incase of session expire.
> - By setting session timeout for 2min and checking that new thread is getting created or not.
> - If a new thread is being created in that case session should not expire till 2min unlike previously.
> - Previous session data was not getting cleared so in case of session expiry the new use was getting created but after every refresh new user was getting created because of older session data present.
> Remove session data incase of session expiry.

- webplugin/js/app/mck-sidebox-1.0.js
-> Removed API calls for message send delivered reports and using the socket connection to send the same.
-> By sending and receiving messages in the chat widget from the dashboard and vice versa.
> CO-647 removed API calls for send and delivery reports for messages

- webplugin/plugin.js
> Add class kommunicate-hide-custom-iframe for Kommunicate.displayKommunicateWidget() function.
> By calling function below function to hide the widget.
Kommunicate.displayKommunicateWidget(false);
-> Class was getting added to the Iframe element but CSS class was not there in the DOM.
> Add class kommunicate-hide-custom-iframe for Kommunicate.displayKommunicateWidget() function.

- webplugin/js/app/mck-sidebox-1.0.js
-> Fixed an issue where the bot message was showing in the UI after the CSAT rating banner if the `botMessageDelay` is active.
> CO-876 Making CSAT banner appear after the same dealy as the bot message reply

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
-> Add customWelcomeEvent in settings, this will be used by bot service to trigger a custom event for the welcome message
Pass  "customWelcomeEvent": "welcome-post-signup" in update settings and verify the group metadata to contain the metadata: CUSTOM_WELCOME_EVENT
->    (function(d, m){
var kommunicateSettings = {"appId":"kommunicate-support","popupWidget":true,"automaticChatOpenOnNavigation":true, onInit: function() {
var defaultSettings = {
"skipBotEvent": '["WELCOME_EVENT"]', // Replace <EVENT_NAME> with the bot platform event names which you want to skip
"skipRouting": true,
"customWelcomeEvent": "welcome-post-signup"
};
Kommunicate.updateSettings(defaultSettings);  
} };
var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
s.src = …
> FW-633 Add support for custom welcome intent in settings

- webplugin/css/app/km-rich-message.css
->  background colour of form submit button in safari browser is different, make it white.
-> tested in safari
> safari fix : background colour fix on form submit button

- webplugin/js/app/mck-sidebox-1.0.js
- Fix bug where attachment icon is coming even if it is disabled using attachment "false"
- Bypassing locShare: true and attachment: false in Kommunicate script.
- The attachment icon was getting enabled without even checking the attachment parameter value. Which when false should not be shown.
> FW-174 Fix bug where attachment icon is coming even if it is disabled using attachment "false"

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/typing-area-dom-service.js
- Fix bug where voice option is coming in the browser which doesn't support it.
- Bypassing voiceInput: true in Kommunicate script and loading it in Chrome, Firefox, and Safari.
- We were calling function to make voice option visible without even checking that it is supported in the browser or not.
> Fix bug where voice option is coming in browser which don't support it.

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Fix issue where maps were not working in the widget.
- By adding **locShare: true** in the widget script.
- The issue was because google maps file was not getting loaded and Maps init function present in sidebox file was get initialized. So until the file is loaded we were checking w.google.maps.
- Added google maps file in external scripts, so the widget will load after all external scripts are loaded. In case locShare is false then we won't load google maps script.
> Fix issue where maps was not working in widget.

- webplugin/js/app/mck-sidebox-1.0.js
- Fix bug, where conversation closed-banner, is not getting removed in real-time when a conversation is reopened from the Dashboard.
- By closing the conversation from Kommunicate dashboard and checking that the conversation closed-banner is getting removed from the chat in real-time.
- This use case was not handled when it was created.
> FW-768 Fix bug where conversation closed banner is not getting removed real-time.

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
-> clear active conversation info from local storage on widget logout and after session expiry
-> 
1. on Kommunicate.logout() call, mckActiveConversation object is cleared 
2. enabled "Remove chat session history on page refresh" on the dashboard,  while initializing the chat widget, mckActiveConversation object is cleared 
> clear active conversation info from local storage on widget logout and after session expiry

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- Fix bug where multiple socket connection getting initialized when launchConversation method is called.
- Socket disconnect time changed from 4min -> 2min.
- By calling launchConversation method in "onInit" callback function.
- Checking the overall socket disconnect feature again.
- Multiple socket connections were getting initialized because of calling the checkConnected method when socket initialization is in progress.
> Fix bug where multiple socket connection getting initialized when launchConversation method is called.

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
> NOTE: Merge when tested in development.
- Fix bug where multiple socket connection getting initialized when launchConversation method is called.
- Socket disconnect time changed from 4min -> 2min.
- By calling launchConversation method in "onInit" callback function.
- Checking the overall socket disconnect feature again.
- Multiple socket connections were getting initialized because of calling the checkConnected method when socket initialization is in progress.
> Fix bug where multiple socket connection getting initialized when launchConversation method is called. [MASTER]

- webplugin/css/app/mck-sidebox-1.0.css
- Fix the issue with message preview alignment when the widget is aligned to the left side
--------
> fix message preview when the widget is aligned to left

- webplugin/css/app/mck-sidebox-1.0.css
-> fix: hyperlink is showing in white colour in the rich text message
-> 
1. Send attachment from the dashboard to plugin, attachment name is showing in white colour(plugin)
2. Send attachment from the plugin to dashboard, attachment name is showing in white colour(plugin)
3. render HTML template with the hyperlink, hyperlink text is showing in black colour.
4. send a link from dashboard
> fix: hyperlink is showing in white color in rich text message

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-message-markup-1.0.js
-> fix: hyperlink is showing in white colour in the rich text message
-> 
1. Send attachment from the dashboard to plugin, attachment name is showing in white color (plugin)
2. Send attachment from the plugin to dashboard, attachment name is showing in white color (plugin)
3. render HTML template with the hyperlink, hyperlink text is showing in black color.
4. send a link from the dashboard
> Fix bug where hyperlink is showing in white color in rich text message. [MASTER]

- webplugin/css/app/mck-sidebox-1.0.css
-> fix: hyperlink is showing in white colour in the rich text message
-> 
1. Send attachment from the dashboard to plugin, attachment name is showing in white color (plugin)
2. Send attachment from the plugin to dashboard, attachment name is showing in white color (plugin)
3. render HTML template with the hyperlink, hyperlink text is showing in black color.
4. send a link from the dashboard
> [Master] fix: hyperlink is showing in white color in rich text message

- kommunicate-script-example/README.md
Need to remove "conversationTitle" and add the Kommunicate chat widget on Pageload doc
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/tree/master/kommunicate-script-example/README.md
-> Add instruction for Kommunicate chat widget on Full screen on Pageload
-> YES
-> Nil
-> Nil
> Need to update chat widget Fullscreen doc

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
-> There was no label defined for the heading on the chat-box for pre-chat-lead-collection. It was still showing 'Conversations' so added a label for that.
> related docs issue: https://github.com/AppLozic/Kommunicate/pull/6327
> Add a title label for the heading of Pre-Chat Lead collection.

- webplugin/js/app/mck-sidebox-1.0.js
-> This PR will fix the issue where the chat widget will not load at all even after refreshing the page after the user was entering the wrong password either in pre-chat lead collection or by passing a variable in KommunicateSettings object.
- Tried logging in through pre-chat lead collection with wrong credentials -> Got the invalid password error -> Refreshed the page -> Was able to load the widget and login again
- Tried logging in by passing credentials from KommunicateSettings object -> Got the invalid password error -> Refreshed the page -> Was able to load the widget and login again
> Fix the issue where chat widget will not load after failing password check

- webplugin/js/app/mck-sidebox-1.0.js
- Fix bug where the message is not rendering when KM_ASSIGN_TO metadata is coming.
- Tested with Dialogflow and Lex bot.
- Case-1 
{
"message": "our agents will get back to you",
"metadata": {
"KM_ASSIGN_TO": "abhinav+testkm27042020@applozic.com"
}
}
**Result**: Message should render in UI.
- Case-2 
{
"metadata": {
"KM_ASSIGN_TO": "abhinav+testkm27042020@applozic.com"
}
}
**Result**: No messge should render in UI.
> Fix bug where message is not rendering when KM_ASSIGN_TO metadata is coming.

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
- Fix the issue where URL coming in carousel type rich-messages coming in the google-assistant based payloads was not mapped in the rich-message displayed in chat widget.
- Set a payload in Dialogflow fulfillment with carousel cards.
- Received the message in chat-widget in the form of a card carousel.
- All the items in the carousel are clickable and redirect to the URL in the payload.
> Add support for link in card carousel on the top of cards

- webplugin/css/app/km-rich-message.css
-> fix google assistant carousel card title and description text overflow issue. **The change is for google assistant based carousel cards.**
-> The following payload needs to passed from dialogflow fulfillment:
`new BrowseCarousel({
items: [
new BrowseCarouselItem({
title: 'Title of item 1ddsfsafsdfsdfsafasffsdfasdfasdfsafsafasfsfsadasdf',
url: 'https://example.com',
description: 'Description of item 1dsfsfsdfasfasdfasdfasdfasdfsadfsadfsafsafsdfsadfsdfadsfasfasdfasdfsadfdasfasdfasdfasdfsafasdfasdfsadfasdfasdfasfasdfadsfasdfsafasdfas',
image: new Image({
url: 'https://storage.googleapis.com/actionsresources/logo_assistant_2x_64dp.png',
alt: 'Image alternate text',
}),
footer: 'Item 1 footer',
}),
new BrowseCarouselItem({
title: 'Title of item 2shdfjsahfkshfksjhfaskhfakjshf',
url: …
> fix google assistant carousel card title and description text overflow issue

- webplugin/js/app/mck-sidebox-1.0.js
- Disable automatic open on navigation for mobile browsers screen on chat widget.
- By checking automatic open on navigation is working for mobile browsers screen. It shouldn't.
- checkIfDeviceIsHandheld function in our code base which is used to identify that browser is on mobile or not.
> FW-1075 Disable automatic open on navigation for mobile browsers screen on chat widget.

- webplugin/js/app/km-utils.js
-> Add SameSite param to sidebox cookies for future chrome release.
SameSite param decides how cookies are stored and treated in cross-origin requests.
This will remove the warnings related to the same - currently displayed in the browser console.
-> Simulated a future release of chrome by setting some flags and checked the if the cookies were being stored.
> Need for this change: https://www.troyhunt.com/promiscuous-cookies-and-their-impending-death-via-the-samesite-policy/
> Add SameSite param to sidebox cookies for future chrome release

- webplugin/js/app/mck-app.js
- Add property to disable/hide the widget.
- Property Name: "disableChatWidget"
- If disableChatWidget is true then Kommunicate widget won't be loaded on the customer website.
- Priority will be given to appOptions if the property is passed in Kommunicate script over appSettings table data.
- By adding the property in chatWidget column in appSettings table and checking that widget is getting loaded or not.
> FW-1099 Add property to disable/hide the widget.

- webplugin/css/app/km-rich-message.css
- Allow longer words [URLs] in most cases to break in away message section.
- Using the following text 
`We are away right now, drop your query and we'll get back soon.
For technical queries, post question on Stackoverflow https://stackoverflow.com/questions/tagged/kommunicate`
> allow word break in away message

- webplugin/js/app/kommunicate-ui.js
-> Add support to automatically render all urls mentioned in away message as actual anchor tag links.
-> Set away message from dashboard with text containing a link and it was displayed as a link while in the chat-widget.
> Add support to convert urls in away message to anchor tag

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/labels/default-labels.js
- Add labels for "hrs ago" || "minutes ago" || "sec ago" in conversation list view in Kommuniate Widget.
- Improve some checks.
- By checking that labels are changing or not.
`
"labels": {
'time.stamp': {
'sec.ago': 'sec ago',
'secs.ago': 'secs ago',
'min.ago': 'min ago',
'mins.ago': 'mins ago',
'hr.ago': 'hr ago',
'hrs.ago': 'hrs ago'
}
}
`
> TD-977 Add labels for "hrs ago" || "minutes ago" || "sec ago" in conversation list view in Kommunicate Widget.

- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- do not call getDomainFromUrl method multiple times
- findCookieDomain method is getting called only once. useful screenshots are attached below.
- getDomainFromUrl method is called multiple places, along with that findCookieDomain method also called. 
- findCookieDomain method tries to find domain by adding "km_{timestamp}" on the cookie and once it is a success, km_{timestamp} be removed from the cookie but chrome always shows deleted cookie in "cookie in use".
**BEFORE** FIX: 
- on screenshot check the "cookie in use" and  browser bottom panel cookies under storage
- **AFTER** FIX:
-  findCookieDomain method should be executed only once when the user loads the script.
> Do not call getDomainFromUrl method multiple times

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- assign the conversation to a particular team by adding parameter teamId .
- KM_TEAM_ID is added into group metadata in below mentioned test cases
- script:
`(function(d, m){
var defaultSettings={"teamId": 7}
var kommunicateSettings = {"appId":"102797803a1e00dccfa83eaf700f2b28a","popupWidget":true,"automaticChatOpenOnNavigation":true, "onInit": function() {Kommunicate.updateSettings(defaultSettings);}};
var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
var h = document.getElementsByTagName("head")[0]; h.appendChild(s);
window.kommunicate = m; m._globals = kommunicateSettings;
})(document, window.kommunicate || {});`
- tested with `Kommunicate.updateSettings(defaultSettings);` and …
> FW 1376 support for teamId

- webplugin/js/app/events/applozic-event-handler.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
- We want to add the functionality of enabling a new option voiceOutput in the chatWidget settings. When it is true, the browser will convert incoming messages to voice and speak them to the user.
Currently, only text messages, location and attachment messages will be converted to voice.
- By running the chat widget and testing incoming messages from the dashboard.
-
-
> Add voice output in chat widget

- webplugin/js/app/mck-app.js
- We want to be able to restrict the chat widget from running on domains that are not inside the list of allowed domains specified by the customer. This PR will check the current host from which the chat widget is running and block if it's not in the specified list.
(if running from localhost then the port number must match too)
- Ran the modified changes locally and tested the results.
-
-
> Disable chat widget if Allowed Domains is set

- webplugin/js/app/mck-sidebox-1.0.js
- pass allowEmail and elasticUpdate params on user update API call 
- allowEmail:true  and elasticUpdate: true params are getting passed on API when the user submits the email on widget.
widget
> pass allowEmail and elasticUpdate params on user update API call 

- package.json
- Bump node-fetch from 2.6.0 to 2.6.1 [security vulnerability]
- https://github.com/node-fetch/node-fetch/releases/tag/v2.6.1
> Bump node-fetch from 2.6.0 to 2.6.1 [security vulnerability]

- webplugin/js/app/mck-app.js
- Add support for voice input/Output parameters from chatWidget object in our Kommunicate Widget.
- First priority is given to appOptions as 'voiceInput" property is live since more than a year and some customer might be using it.
- By updating the "voiceInput" and "voiceOuput" property from the settings update API and check whether both features are working fine or not.
> TD-1260 Add support for voiceInput/voiceOutput parameters from chatWidget object in our Kommunicate Widget.

- webplugin/js/app/media/media-service.js
- Add a valid BCP-47 language code inside the kommunicate settings option. This will be used for speech-to-text if supported by the browser.
Ref this issue: https://applozic.atlassian.net/browse/FW-1612
If language is not supported, speech-to-text will not work.
- {"voiceInput": "true", "language": "hi-IN"}
The input speech will now be converted to Hindi text.
-
-
> Add language option in chat widget to use to speech recognition

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- Remove default agent from adding as admin or assignee to a conversation. The conversation will be routed through routing rules and the admin and assignee will be added accordingly.
- By default, super admin is getting added into all conversation, by these changes, it will be prevented. 
- tested locally by seeing the presence of super admin. It should not be present in conversation until the super admin is not select into routing rules. 
- or until a super admin is not getting added directly from the installation script
> remove default agent id from create conversation payload

- webplugin/js/app/media/media-service.js
- Use the same language option for STT in TTS also. Also don't throw error when it occurs because of user activation.
https://stackoverflow.com/questions/54265423/javascript-speechsynthesis-speak-without-user-activation-is-no-longer-allowed
- { "voiceOutput" : "true", "language": "de-DE"} 
- Incoming message `Auf welche Branchen ist Protection One spezialisiert?` will be spoken in german.
-
-
> Add language option in TTS and don't print error for not-allowed

- webplugin/plugin.js
- To enable the full view of widget in mobile browsers when the widget is aligned left.
-
-
-
> TD-1370 Mobile browser not showing the full view of chat widgets

- webplugin/js/app/mck-sidebox-1.0.js
- To fix an issue raised by VOGO in which following error was shown err_cleartext_not_permitted
-
-
- Cleartext is any transmitted or stored information that is not encrypted or meant to be encrypted. When an app communicates with servers using a cleartext network traffic, such as HTTP, it could raise the risk of eavesdropping and tampering of content. Third parties can inject unauthorized data or leak information about the users. That is why developers are encouraged to secure traffic only, such as HTTPS. Starting with Android 9.0 (API level 28), cleartext support is disabled by default. Due to security purposes URL without HTTPS will throw err_cleartext_not_permitted error whenever an application uses it in the Android webview.
There’s an easy solution to fix err_cleartext_not_permitted …
> fix this error [err_cleartext_not_permitted] [VOGO]

- webplugin/css/app/km-rich-message.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Support functionality for hiding the buttons once the user has clicked on it. (quick reply buttons only)
- Create a global settings for enabling hiding list / quick reply btn.
- The end user is prompted with following options
- He click on any option, then the all other option expect link should hide (for this example clicked on btn2)
- If no link btn is present then whole msg should hide
-
- 
> TD-1514 Hide List and button in a rich message on click

- webplugin/js/app/mck-sidebox-1.0.js
- fix the issue were the messages were rendering in reverse order and bot messages were not showing
- fix for the vogo's query regarding the csat rating emoji issue.
- Create and intent having multiple messages.
( have minimum 5 - 6 messages so that it takes around 2, 3 seconds to render )
- open the widget
- type the training phrase as configured for the intent made above.
- press enter and immediately switch the internet connection off. ( response should not have been loaded completely)
-  wait for 30s and reconnect the internet.
- the messages should appear in order. (not in reverse, or hidden in case for bots' response)
If bug exists then messages will render as show in the video
https://user-images.githubusercontent.com/19753380/108473109-9df93700-72b3-11eb-9fc7-538a2331e645.mov …
> TD-1564 BUGFIX For the reverse message order issue. [DEVELOPMENT]

- webplugin/js/app/mck-sidebox-1.0.js
* updated http to https for location (#599)
* Update mck-sidebox-1.0.js
* bug fix for following case
Upon socket reconnection, the messages were rendering in reverse order, and bot messages were not visible
-
-
-
-
> TD-1564 BUGFIX For the reverse message order issue. [PLUGIN-6.5] (#624)

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- To fix the bug where the UI was breaking for the case of team handoff if the message was empty.
- Create a team handoff intent without the message property in the payload.
- trigger the intent from the chat widget 
- the conversation should get assigned as per the set payload and the bot image should not be cut as shown in the example figure. 
- If no message is their then the user will not see any thing. Only the conversation gets assigned.
- 
- 
> FW-1957 Bot image is half cut if team handover is taking place [BUGFIX]

- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- To add security for image files.
- add attachment: true in kommunicate settings
- start new conversation and upload an image
- the image should upload
- go back and reopen conversation
- the image should load and upon clicking the image the modal containing image should open
-
-
INTRODUCTION TO THE ISSUE:
As of now all the images uploaded to aws server can directly be accessed using the url provided by them. 
To avoid this, aclsPrivate parameter is passed as true. 
Now in order to access image, we need to pass blobkey which will gives us the link for the particular image. The provided link is only accessible for 15 mins.
> FW-2052 Access files signed URL in web plugin [Security, Important]

- webplugin/js/app/kommunicate-ui.js
- Bot message auto-scroll when waiting queue message is shown.
- Enable waiting queue then start a conversation put a conversation in the waiting queue.
- Check for message body is has to scroll down for multiple bot messages.
---
-
- Auto scrolling was not managed while showing the waiting queue message.
> FW-2159 Bot messages should auto-scroll when waiting queue message is shown [Chat-Widget]

- webplugin/js/app/mck-sidebox-1.0.js
- The encrypted images should distinguishable from non-encrypted images.
- Both encrypted and non encrypted images should open.
- The videos should be handled 
- open chat widget using plugin-6.6.4 or lower upload image A.
- open chat widget using this branch upload image B
- upload a video from this branch 
- all the three media should be visible in the chat widget
- 
-
> FW-2226 Make improvements in the file encryption logic in chat widget

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- Add a support of group metadata on start conversation function.
- Use the below script to test the functionality.
```
(function (d, m) {
var kommunicateSettings = {
appId: "8ced8a81108c654234a393115cc2ea4f",
popupWidget: true,
onInit: function () {
var conversationDetail = {
conversationMetadata: {
"key1": "honda",
"key2": "city",
},
};
Kommunicate.startConversation(
conversationDetail,
function (response) {
console.log("new conversation created");
}
);
},
};
var s = document.createElement("script");
s.type = "text/javascript";
s.async = true;
var h = document.getElementsByTagName("head")[0];
h.appendChild(s);
window.kommunicate = m;
m._globals = kommunicateSettings;
})(document, window.kommunicate || {});
```
---
-
-
NOTE: Make sure …
> FW-2044 Add group metadata support in start conversation | chat widget

- webplugin/js/app/km-richtext-markup-1.0.js
- HidePostCTA is not working for Dialogflow.
- Select any Dialogflow bot and set the hidePostCTA to `true` in script settings.
- check if hidePostCTA is working fine or not.
https://user-images.githubusercontent.com/22856546/118983735-5eb5b180-b99a-11eb-8550-b1fd7f797fc1.mov
-
- Markup return for the Rich message is not having the proper class name
> FW-2221 HidePostCTA is not working for Dialogflow [Fix]

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- Show CSAT close button only when user click on the Rate conversation button in chat widget side.
- Parent PR: (#692)
---
https://user-images.githubusercontent.com/22856546/122930433-9f359000-d389-11eb-8780-f7ea4592d2b0.mov
-
-
> Fix close button in feedback banner [chat-widget]

- webplugin/css/app/mck-sidebox-1.0.css
- Fix overflow for IE in quick replies menu.
---
-
- CSS property is not compatible with IE.
> Fix overflow for IE in quick replies menu [Chat widget]

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- Kompose bot stuck in the middle if the conversation is too long.
- Check for scrolling of long messages in chat widget.
---
https://user-images.githubusercontent.com/22856546/125408305-690f8d00-e3d8-11eb-9608-5758d593d2de.mov
-
-
> FW-2482 Kompose bot stuck in the middle if the conversation is too long [Chat widget]

- webplugin/js/app/km-widget-custom-events.js
- Send chat widget events to Google Analytics.
- Parent PR: https://github.com/Kommunicate-io/Kommunicate-Dashboard/pull/698
- Track all events are sending to the Google Analytics from the chat widget by setting GA TRacking Id from both side( kommunicateSettings or dashboard settings).
---
https://user-images.githubusercontent.com/22856546/125790787-267c2c6e-0936-4da2-b228-fcb84ee25d2c.mov
-
-
> FW 2458 Added support for Google Analytics traking id from dashboard [chat widget]

- webplugin/js/app/kommunicate-ui.js
- Restart conversation button is missing if CSAT rating is disabled and the agent Resolves the chat bug fix 
- [] I have tested it in IE Browser.
- Disable CSAT from the dashboard 
- Start the conversation from widget 
- Resolve the conversations from Dashboard
- Restart conversation button link should show on the chat widget 
-
-
> FW-2485 Restart conversation button is missing if CSAT rating is disabled and the agent Resolves the chat

- webplugin/css/app/km-login-model.css
- Make scroll bar visible when required.
- scroll bar should be having thin width similar to chrome
- enable prechat lead collection
- go to any random site and initiate chat widget
- the prechat lead form will have scroll bar only if the form is long
- the scroll bar will have appearance similar to that of chrome
-
-
> FW-2475 Make scrollbar of pre-chat lead collection same as Chrome for Firefox [Chat-widget]

- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/labels/default-labels.js
- Remove "Here is the llink"  text from the link preview.
- Check for the "Here is the link" in link preview.
---
-
-
> Fix remove extra text from the link preview [Chat widget]

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate.js
- Add support of Form inputs in chat transcript.
-  Use this new property `"postFormDataAsMessage": "true"` inside the `action ` of form templete.
```
"action": {
"message": "Submit details",
"requestType": "postBackToBotPlatform",
"postFormDataAsMessage": "true",
"formAction": "https://reqres.in/api/users"
}
```
- Click on send transcript to user button in the conversation section and check for form data in the chat transcript.
---
https://user-images.githubusercontent.com/22856546/132954722-b7d1ebdc-182f-4351-bbbf-06cc5213000b.mov
-
-
> FW-2740 [Important] Add Form inputs in chat transcript 

- server/config/config-env.js
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- Add the Video Capture button on the Chat widget for mobile devices.
- Set  `captureVideo:true` in the kommunicateSettings. Now, you will see a video recording icon inside the chat widget.
- Try to record a video and send it on the chat.
---
https://user-images.githubusercontent.com/22856546/134118448-0663881a-9238-4349-ad56-149661a83aa2.mov
-
-
> FW-2676 [Imp] Add video capture on Chat widget.

- webplugin/js/app/km-post-initialization.js
- The category should not be displayed in the faq section of widget if the category has no published articles
- add categories such that it has either no articles or it has unpublished articles 
- these articles should not appear in faq category
-
-
> FW-2731 Don't show the Category in FAQ in chat widget if it has zero articles

- server/config/config-env.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
- webplugin/pluginOptimizer.js
- Add basic functionality for zendesk chat integration
- Customer can pass `zendeskApiKey` or save it in the app settings API. Key passed in the script will have priority over key saved in app settings API.
- Functionalities added:
- initialize zendesk-zopim sdk
- For now, the first message is hardcoded, having dashboard link, but in future, we will attach chat transcript for Zendesk Agent's reference and provide chat context.
- send user messages to zendesk agent
- receive agent messages and console log them
- There are some complications in sending agent messages to Kommunicate. We will do that separately.
```curl
curl --location --request PATCH 'https://api-test.kommunicate.io/rest/ws/settings/application/detail' \
--header 'authorization: {{authorization}}' \
--header 'Content-Type: …
```
> Zendesk chat integration ground work

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/mck-app.js
- Add a feature where the form would get hidden once it gets submitted.
- create a bot having from
- initialise the widget with `hidePostFormSubmit: true` in kommunicateSettings
- submit the form
https://user-images.githubusercontent.com/19753380/140905699-e578582c-6792-4947-8f90-bf4cdf6da289.mov
-
-
> FW-3047 Hide form submit button post submission [Important]  

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
- add agent message flow for zendesk chat integration. in this we will call a new send message API, which will accept zendesk userId, message, groupId and send those to particular conversation.
- In the below image, notice agent messages from zendesk chat dashboard are being shown in the km widget
- https://github.com/Kommunicate-io/Kommunicate-Server/pull/363
> add agent message flow for zendesk chat integration

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- banner should be visible if socket reconnect fail count is > 2
- 
-
-
> FW-3132 A banner should be visible if socket connection drops

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/819
1. fixed bug where the 3 dot button icon was coming on contact list page in a specific scenario
2. fixed a bug where the no results found view was overlapping with faq categories view
> [BUGFIX] FW-3097 

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
- The away messages functionality should work as aspected.
1st 
- turn on away message and collect email
- go to conversation rules 
- turn of bot routing
- create a new chat widget instance and start a conversation
- the user should be prompted to input email when he send a message
2nd 
- turn on away message and collect email
- go to conversation rules 
- turn on bot routing
- create a new chat widget instance and start a conversation
- handoff the conversation to human agent (via handoff btn)
- the user should be prompted to input email when he send a message
-
-
> FW-2422 Fix collect email id functionality in away and welcome messages

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- The input fields should be disabled upon form submission
- submit button should hide
- The submitted details should appear in the form if chat is reloaded
- pass disableFormPostSubmit: true in kommunicateSettings
-
-
> FW-3499 The form should be disabled post submission

- webplugin/js/app/zendesk-chat-service.js
- add support to pass user information to zendesk.
- with these changes, user display-name, email will get reflected in zendesk chat side.
- There are 2 changes in this PR:
1. Created an API in the server to get JWT.
2. Pass server-generated JWT to zendesk SDK.
- in below snip notice user's name, email is coming in zendesk.
https://github.com/Kommunicate-io/Kommunicate-Server/pull/406
> add support to pass user information to zendesk

- webplugin/js/app/zendesk-chat-service.js
- bugfix of chat widget going into infinite loop if bot routing is not enabled
- disabled bot routing and checked widget logs. Earlier it used to just go into infinite loop now it stops after 2 create event.
- In below image notice on tab clicked event is coming just 2 times. this is the one which used to come infinitely.
> bugfix of chat widget going into infinite loop if bot routing is not enabled

- webplugin/js/app/km-post-initialization.js
- if only one article is present then show the list of articles directly
- if none of the categories have articles inside them then don't show FAQ button.
- create single / multiple categories from dashboard
- open the chat widget 
- previously the faq button would be visible and upon clicking, a black page would appear. Now FAQ button will not appear
- if only one category is present then the list of articles would be displayed instead of one category card.
-
- 
> FW-3201 FAQ is displayed in the Chat widget if there is a caterogy without a single article

- webplugin/js/app/zendesk-chat-service.js
- In Zendesk chat transcript, Bot name should show instead of bot id
- Tested locally. worked fine. 
> [TD-2506] Bot name should show instead of bot id [zendesk chat]

- webplugin/js/app/kommunicate-ui.js
-Chat Widget Should work like Zendesk Chat where if we end chat in zendesk zopim chat and click restart conversation on chat widget a new conversation should just like how it is on zendesk
-integrate zendesk, run chat widget locally and check if messages are coming on zopim chat or not after which end conversation from zendesk. try restarting conversation to check if a new conversation is starting or not
-
-
> [TD-2686] Chat widget should work like Zendesk

- webplugin/js/app/mck-sidebox-1.0.js
- Acknowledge the APPLOZIC_33 message type and hide the deleted message
- start a conversation.
- send a message and reply from the dashboard side.
- delete the message from dashboard. 
- the message should not be displayed in chat widget.
Note:
1. to see the change on dashboard side please make sure that the changes mentioned in [this PR](https://github.com/Kommunicate-io/Kommunicate-Dashboard/pull/1161) are live.
-
-
- https://fw-3825.netlify.app/
> FW-3825 Delete user's messages from the dashboard and chat widget

- webplugin/js/app/km-widget-custom-events.js
- webplugin/js/app/mck-sidebox-1.0.js
- if we add custom events through chat-widget installation script, then those custom events were not working if we integrate Zendesk. Fixed it in this PR.
- Tested locally by trying custom events with Zendesk integrated. Verified that both sets of events are working properly.
- The installation script I tried is 
```
(function(d, m){
var kommunicateSettings = 
{"appId":"1db8ab434f82ca912605d08c3f93c8a0f","popupWidget":true,"automaticChatOpenOnNavigation":true};
kommunicateSettings.onInit = () => {
var events = {
"onMessageReceived": (response) => {
console.log("response1 for onMessageReceived", response);
},
"onMessageSent": (response) => {
console.log("response1 for onMessageSent", response);
},
"onSubmitRatingClick": (response) => {
console.log("response1 for …
```
> [TD-2761] Fix for 'Chat-widget events not working for Zendesk integration'

- webplugin/js/app/mck-sidebox-1.0.js
- The widget was getting stuck in loading state when the back button was getting clicked
- this was happening in the normal flow
- Created a multiple conversations in the normal flow
- created multiple conversations in zopim flow.
-
- a check was missing for the groupFeeds array
> Fix the bug where the widget stuck in loading state on click of back button

- webplugin/js/app/mck-sidebox-1.0.js
- If the encrypted user uses the pre-chat lead then API is not encrypted in type 3 and in type 5 widget not opening
- this is because we don't ` enableEncryption` property in the payload
- Test for pre chat encrypted account [type 3,5]
- without prechat lead in encrypted account
- Test without encrypted account also
-
-
>  If the encrypted user uses the pre chat lead then API is not encrypted in type 3 and in type 5 widget not opening

- webplugin/js/app/mck-sidebox-1.0.js
-Language codes for non-welcome messages should come to bot server
-Locally
-
-
- Before 
- After
> TDH-62 Language code for non welcome msgs are not coming to bot server by default

- webplugin/css/app/mck-sidebox-1.0.css
- The text cursor should appear every time
test case 1
- copy a white html text and paste in the input box
- the text caret should appear
test case 2
- watch the video mentioned in the comments of the ticket
-
- We're using contenteditable div as text input and css was not configured properly
- We’re using :before to show placeholder. On clicking the placeholder the focus is not happening.Pseudo-elements are not part of the DOM at all so we can't bind any events directly to them.  
- 
> FWH-98 Some times when we click on the text area in the chat widget the Text Cursor doesnot appear

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Add support for showing custom message if file limit is exceeded
- There are a total of three base cases
1. Test the widget normally
2. Test the widget after making changes in appSettings table 
3. Test the widget after adding changes in kommunicateSettings
The default limit for file upload is 25 mb and the message displayed is File size cannot be more than $maxAttachmentSize MB
This can be now changed. 
One can update the chat_widget column in appSettings table in DB or he/she can provide the below mentioned properties in kommunicateSettings while initialising the script
Sample of the properties
maxAttachmentSize: 25
maxAttachmentSizeErrorMsg: "File size cannot be more than $maxAttachmentSize MB"
Note if $maxAttachmentSize is provided then it will get replaced to the value
-
-
- 
NOTE: …
> FWH-525 Add support for showing custom message if file limit is exceeded

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- When a chat is initiated for a new user for the first time, in some cases the pseudonym assigned to that user is displaying in place of his/her name in the chat.
- By running the widget in my local host and changing the config-env.js file to use my local code for testing in Chrome browser. 
- Asynchronous network calls and functional programming
- The cause of the problem was the updateUser function. This function is an asynchronous function which uses AJAX to send a request and await its response, but also it lets the javascript code to move forward irrespective of its response. The code doesn't wait for the response.
- So what's happening is, in some cases the send message request is getting processed before the updateUser request due to which the entity extractor is extracting the …
> TDH-338 Pseudonym appearing in place of Name in first chats sometimes

- webplugin/js/app/mck-app.js
- updated api version
- Deploy https://github.com/Kommunicate-io/Kommunicate-Server/pull/794
- check conversations across various platforms
-
-
- 
> FWH-514 Mask agentId field in users/v2/chat/plugin/ api - should be backward compatible

- webplugin/js/app/mck-sidebox-1.0.js
- if we add space in the field name of the pre-lead collection,then the collected data of that input field is not visible in the user info section.
- replaced space with "-".
-
-
-
- 
> replaced space with -  in field name CUS-293

- webplugin/js/app/mck-sidebox-1.0.js
- Add hard check to disable any conversation summary summary message in widget conversation list and message list
- Tested locally
- Message received after talk to human button is click doesn't contain hidden in metadata. Now, we are returning if it contain KM_SUMMARY so that no message which contain this field is added to the widget. 
- after fix
- before fix 
> Fix conversation message on message 

- webplugin/js/app/mck-sidebox-1.0.js
- Fix business hour banner issue.
- locally.
- The issue is when agents are out of business hour then we show them a banner but if end user send any message at that time banner was getting hidden if end reload the page or open widget again after closing then we show them that banner again. 
Fixes: Now if agents are out of business hour then it will always show them banner even if end user sends message.
- 
> CUS-848 Out of business hour banner fixes.

- webplugin/js/app/mck-sidebox-1.0.js
- Fixed Email validation error
- Locally
- The root cause of the bug is related to the messageSentToHumanAgent counter variable's incorrect increment timing. When a user enters an invalid email, even though the validation fails, the counter messageSentToHumanAgent still gets incremented due to the line:
`!KommunicateUtils.isCurrentAssigneeBot() && messageSentToHumanAgent++;`
This increment happens regardless of email validation success or failure. As a result, when the user tries to enter the email again, the condition: `messageSentToHumanAgent == 1` is no longer true (since it's now > 1), causing the validation logic to be skipped entirely. This prevents the error message from being shown/hidden appropriately on subsequent email entry attempts.
The counter should only be incremented when …
> CUS-908 Email validation error

- webplugin/js/app/mck-sidebox-1.0.js
- Instead of Assignee change api now we will use send message api. Because assignee change api will always change assignee but if bot to human handover is off when agents are away/offline in that case we want to show away message too
-
-
-
- 
> Tdh 1776 Restrict Human Handover
