- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
> Adding method to update user's timezone from chat widget

- .gitignore
- webplugin/pluginOptimizer.js
> Create .gitIgnore file and added config environment for build file.

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
->
-> By uploading an image and clicking on that uploaded image to open its preview
->
-> Fixed a bug where `parent.document` was throwing error that it cannot find the id of a particular div. This was happening due the presence of nested iframes. This is fixed here by replacing `parent.document` with `window.top.document`
> Fix classLsit of null error for opening image in fullview

- webplugin/js/app/mck-sidebox-1.0.js
->Fix script execution when audio/video tag passes as a msg
->
->
->
> #audio video tag fix[Master merge]

- .gitignore
- .vscode/launch.json
->Add vs_code launch configuration
->Add folder in gitIgnore.
-> By running node server via vs_code debugger.
> Add vs_code launch configuration and add folder in gitIgnore.

- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
->  in case of automaticChatOpenOnNavigation, before opening the chat thread compare the User id
->
if automaticChatOpenOnNavigation : true
load the script
reload browser tab, without closing the chat widget
re-load the script after clearing the cookies.
conversation thread not loading
->
->
> KM-2341- fix: multiple users able to send a message in one group

- webplugin/js/app/km-utils.js
-> code improvement: remove if condition
->
->
->
> code improvement: remove if condition

- webplugin/js/app/mck-sidebox-1.0.js
1. These are the only changes which we need to do in kommunicate repo.
2. Have done the changes in applozic web-plugin side, they are currently being tested. Once the changes are approved will change the minified file URL for kommunicate.
3. Will test and check once URL is changes.
> KM-2363 Add Application-User header in all APIs [MASTER]

- webplugin/js/app/mck-sidebox-1.0.js
1. These are the only changes which we need to do in kommunicate repo.
2. Have done the changes in applozic web-plugin side, they are currently being tested. Once the changes are approved will change the minified file URL for kommunicate.
3. Will test and check once URL is changes.
> KM-2363 Add Application-User header in all APIs [RELEASE]

- webplugin/css/app/mck-sidebox-1.0.css
- To fix message flicker in IOS devices
> CO-483 Messages getting hidden in iOS browser [MASTER]

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
1. Update minified file URL to version 5.5.2
2. In logout function Kommunicate key was getting deleted from local storage which was not even present there, it is present in session storage.
3. Remove function which was clearing session storage and added a new function which will remove keys which are added by us only.
-> By performing logout using globally exposed logout function.
> Fix minor bugs and update minified file URL [RELEASE]

- webplugin/js/app/mck-sidebox-1.0.js
- Fix the undefined error coming up when user was submitting CSAT comment 
->
->
->
> fix undefined error in CSAT rating

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
1. Update minified file url to version 5.5.2
2. In logout function kommunicate key was getting deleted from local storage which was not even present there, it is present in session storage.
3. Remove function which was clearing session storage and add new function which will remove keys which are added by us only.
> Fix minor bugs and update minified file URL [MASTER]

- webplugin/js/app/mck-sidebox-1.0.js
-> bug: create preLeadCollection with field name starts with a capital letter, field and value is not getting added into metadata
->
->
-> replaced filter with map 
> KM-2402: [Release] fix: lead collection data is not getting added in user metadata

- webplugin/js/app/km-richtext-markup-1.0.js
> KM-2406: Suggested Reply btn text sholud be shown "name" parameter

- webplugin/css/app/km-rich-message.css
-> change the font size of quick reply in the generic card
->
->
->
> generic card - quick rpy style fix

- webplugin/plugin.js
> Changing let to var for testing chat plugin in older browsers

- webplugin/js/app/km-rich-text-event-handler.js
> remove svg global variable

- webplugin/js/app/mck-sidebox-1.0.js
> CO-272 fix title not reverting back to old title on tab focus [MASTER]

- webplugin/js/app/mck-sidebox-1.0.js
> CO-272 fix title not reverting back to old title on tab focus [RELEASE]

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- webplugin/knowledgebase/kb.js
->replace kb search to elastic search 
->
->
->
> replace kb search to elastic search [Release]

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- webplugin/knowledgebase/kb.js
->replace kb search to elastic search
-> By searching faq from sidebox plugin.
->
->
> #KM-2172 replace kb search to elastic search

- webplugin/js/app/km-attachment-service.js
- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/knowledgebase/kb.js
-> To achieve better cross-browser compatibility all the instances of let are changed to var
> change let to var for better cross browser compatibility

- kommunicate-script-example/README.md
> Update README.md for Kommunicate Full screen widget demo

- webplugin/js/app/mck-sidebox-1.0.js
-> Maximize the body's width once the widget opens as the body becomes a fixed element and the height collapses in case of no elements present in the body
> maximize body size on widget open [RELEASE]

- webplugin/js/app/mck-sidebox-1.0.js
-> Maximize the body's width once the widget opens as the body becomes a fixed element and the height collapses in case of no elements present in the body
> maximize body size on widget open [MASTER]

- webplugin/plugin.js
> Fixed IE issue of iframe not resizing on close of sidebox [RELEASE]

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
-> By sending a message in sidebox and clicking on the notification that pops up on the new message. 
-> By closing and opening the notification popup and sidebox.
->
-> The main bug was removing multiple classes from the HTML tags by using `classList.remove("class-a", "class-b", "class-c")`. Multiple addition and removal form classList is not supported in IE.
-> 
> Fixed IE issue of iframe not resizing on close of sidebox [MASTER]

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
> Fix iframe resizing issue in IE [RELEASE]

- webplugin/css/app/mck-sidebox-1.0.css
> Fix text overflowing beyonf notification box height when new message arrives [MASTER]

- webplugin/css/app/mck-sidebox-1.0.css
> Fix text overflowing beyond notification box height when new message arrives [RELEASE]

- kommunicate-script-example/README.md
> Fix iframe blocking webpage issue with full screen widget

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/pluginOptimizer.js
-> Fix API failing because of encryption enabled
-> Remove console.log for test and prod builds. [RELEASE]
-> By running Kommunicate install script.
-> drop_console (https://github.com/mishoo/UglifyJS2)
> Fix API failing because of encryption enabled and remove console.log for test and prod builds. [RELEASE]

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/pluginOptimizer.js
-> Fix API failing because of encryption enabled
-> Remove console.log for test and prod builds. [RELEASE]
-> By running Kommunicate install script.
-> drop_console (https://github.com/mishoo/UglifyJS2)
> Fix API failing because of encryption enabled and remove console.log for test and prod builds.[MASTER]

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix bug where after logout from sidebox it was net getting visible after reinitialization.
Step-1 Run Kommunicate install script.
Step-2 Run **var options = window.applozic._globals** in broswer console.
Step-3 Run **Kommunicate.logout()** in browser console.
Step-4 Run **window.$applozic.fn.applozic(options)** in broswer console.
Now sidebox should be visible, in production you can run the same and see that it won't be visible after performing the above steps.
-> While performing logout we were hiding the iframe but while reinitializing it we were not making it visible.
> Fix bug where after logout from sidebox it was net getting visible after reinitialization.

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix bug where after logout from sidebox it was net getting visible after reinitialization.
Step-1 Run Kommunicate install script.
Step-2 Run **var options = window.applozic._globals** in broswer console.
Step-3 Run **Kommunicate.logout()** in browser console.
Step-4 Run **window.$applozic.fn.applozic(options)** in broswer console.
Now sidebox should be visible, in production you can run the same and see that it won't be visible after performing the above steps.
-> While performing logout we were hiding the iframe but while reinitializing it we were not making it visible.
> Fix bug where after logout from sidebox it was net getting visible after reinitialization. [MASTER]

- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
->adding support for mixing suggested replies, link and submit button
->
->
->
> adding support for mixing suggested replies, link and submit button

- webplugin/js/app/mck-sidebox-1.0.js
-> CO-536 Remove delete/reply option for message in sidebox.
> CO-536 Remove delete/reply option for message in sidebox.

- webplugin/controller.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/pluginOptimizer.js
-> Store file data version wise in object and pass it directly as per server request.
-> By running script for both v1 and v2 versions.
-> [util.promisify()](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original)
> CO-657 Store file data version wise in object and pass it directly as per server request.

- webplugin/js/app/media/typing-area-dom-service.js
> [RELEASE] showing mic button if setting is enabled

- webplugin/js/app/media/typing-area-dom-service.js
> [master] showing mic button if setting is enabled

- webplugin/js/app/mck-app.js
-> Remove arrow functions from mck-app.js file.
> Remove arrow functions.

- webplugin/js/app/mck-app.js
-> Remove arrow functions from mck-app.js file.
> Remove arrow [RELEASE]

- webplugin/js/app/mck-app.js
-> Remove arrow functions from mck-app.js file.
>  Remove arrow functions.[MASTER]

- webplugin/pluginOptimizer.js
-> Add drop_console and keep_fnames for mck-app.js file.
-> By creating a build for test environment and checking sidebox working or not.
> Add drop_console and keep_fnames for mck-app.js file.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
1. Add hover text on rating emoji.
2. Add emoji hover text in labels.
3. Minor CSS fixes.
> Add hover text on rating emoji's and minor CSS fixes.

- webplugin/js/app/mck-app.js
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
> Replace innherHTML with insertAdjacentHTML.

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
> Update assignee when changed from the dashboard realtime in chat.
> Made common function to set conversation header in sidebox.
> Create conversation.
> Change assignee for the conversation from dashboard.
> Assignee should also change in the sidebox conversation header.
> CO-649 Update assignee realtime in chat.

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix bug where utm_source was getting passed null because of the iframe.
> **URL: ** https://www.kommunicate.io/?utm_source=http://localhost:8080/widget.html&utm_medium=webplugin&utm_campaign=poweredby
> **utm_source**: http://localhost:8080/widget.html
> Fix bug where utm_source was getting passed null because of iframe.

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
-> create a form in  actionable message
->
->
->
> TD-172: actionable message- form

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
> actionable message- form [development]

- webplugin/js/app/km-richtext-markup-1.0.js
> change let to var

- webplugin/js/app/km-utils.js
> corrections in isURL method

- webplugin/js/app/mck-sidebox-1.0.js
> fix: KM_CHAT_CONTEXT getting appended with app messages

- webplugin/js/app/km-richtext-markup-1.0.js
> using message property in quick reply if available

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
>  actionable message- form [Master] - Testing is WIP

- webplugin/js/app/km-richtext-markup-1.0.js
> [MASTER] using message property in quick reply if available

- webplugin/js/app/mck-sidebox-1.0.js
code is merged in master, not in the development branch
->
->
->
->
>  catch error from howler

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
> link button fix [Development]

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
->
-> button template. combine different types of buttons, list template, card carousel are tested
->
->
> handlleRichButtonClick method improvements [development]

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
> link button fix [Master]

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
->
->
->
https://stackoverflow.com/questions/45634088/how-to-prevent-page-from-reloading-after-form-submit-jquery
solution 2 is used here for the fix
->
> fix: on form submit new tab is getting opened

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
> [Master] fix: on form submit new tab is getting opened

- webplugin/js/app/kommunicate-client.js
->add group_creation_url in group metadata
->By creating a new group.
->
->
> #FW-102 add group_creation_url in group metadata

- webplugin/js/app/mck-sidebox-1.0.js
> warning still showing in agent chat fix

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
-> Removed outline when clicking on chat launcher, messages or any conversations. Instead, added event listeners only when someone is navigating the chat widget using arrow keys.
-> By navigating the chat widget using arrow keys and mouse.
> CO-773 Removed outline when clicking on any elements in sidebox chat widget

- webplugin/css/app/mck-sidebox-1.0.css
-> By typing in the typing area and seeing that no outline appears.
->  Fix Outline issue in Typing area of sidebox
> CO-773 Fix Outline in Typing area of sidebox

- webplugin/js/app/mck-sidebox-1.0.js
->add setting to change received message color
-> By adding secondaryColor using appsetting patch API then verified it in the plugin.
->
->
> #FW-170 Setting to change received message color

- webplugin/js/app/mck-sidebox-1.0.js
Reverts Kommunicate-io/Kommunicate-Web-SDK#139
> Revert "#FW-170 Setting to change received message color"

- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
> setting for received msg color and send feedback rating as msg

- webplugin/js/app/events/applozic-event-listener.js
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
> Setting for received msg color and feedback changes for dashboard

- webplugin/js/app/events/applozic-event-listener.js
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
> setting to add receive msg color and feedback changes for dashboard

- webplugin/js/app/mck-sidebox-1.0.js
> #add you in label

- webplugin/js/app/events/applozic-event-listener.js
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
> Release plugin 5.0

- webplugin/js/app/events/applozic-event-listener.js
- webplugin/js/app/mck-sidebox-1.0.js
> #add skipbot metadata

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
> Update logout function and remove all script tags on logout.
> By calling Kommunicate.logout() and reinitializing Kommunicate from console.
> Update logout function and remove all script tags on logout.

- webplugin/plugin.js
-> Throw error if the iframe is already loaded.
> Throw error if iframe is already loaded.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
-> Removed outline when clicking on chat launcher, messages or any conversations. Instead, added event listeners only when someone is navigating the chat widget using arrow keys.
-> By navigating the chat widget using arrow keys and mouse.
> CO-773 Removed outline when clicking on any elements in sidebox chat widget [RELEASE]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
-> Removed outline when clicking on chat launcher, messages or any conversations. Instead, added event listeners only when someone is navigating the chat widget using arrow keys.
-> By navigating the chat widget using arrow keys and mouse.
> CO-773 Removed outline when clicking on any elements in sidebox chat widget [MASTER]

- webplugin/js/app/mck-app.js
> - Comment the code because this code is of no use as it was added 5 months back and it was added only just to replace the cookies of all our customer with the new structure of our cookies.
> - Rename the function loadPseudoName to getApplicationSettings in mck-app.js file.
> - Update Applozic minified file version in Kommunicate-SDK.
> CO-734 Comment code which was replacing older cookies with new structure.

- webplugin/js/app/mck-sidebox-1.0.js
-> adding rich message icon regardless of message is present or not.
->
->
->
> adding rich message icon regardless of message is present or not.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
-> Added popup widget design in sidebox as shown in the screenshots below.
->
> CO-173 Conversation starter popup in chat widget UI in chat widget

- webplugin/js/app/mck-sidebox-1.0.js
> Remove message list API call on Create group.
> By creating the group and re-opening it after going back to list view using the back button in sidebox.
> After the group was created, message list API call was going and parallelly same messages were received from socket also. So sometimes message order issue was coming because of that as in case message list we prepend the message and in case of the message received from the socket, we append the messages on by one.
> CO-681 Remove message list API call on Create group.

- webplugin/css/app/km-sidebox.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
-> Added delay in the messages coming from a bot.
-> To enable these settings just pass `botMessageDelay` in the appOption like so: `botMessageDelay: 2000`, where 2000 can be the amount of time (in milliseconds) the delay has to be shown.
-> By adding multiple welcome and follow up messages in bot.
-> By enabling and disabling `botMessageDelay` appOption from install script.
Thanks to @ab14bhardwaj 
> CO-775 Added dealy for messages from bot [RELEASE]

- webplugin/css/app/km-sidebox.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
-> Added delay in the messages coming from a bot.
-> To enable these settings just pass `botMessageDelay` in the appOption like so: `botMessageDelay: 2000`, where 2000 can be the amount of time (in milliseconds) the delay has to be shown.
-> By adding multiple welcome and follow up messages in bot.
-> By enabling and disabling `botMessageDelay` appOption from install script.
Thanks to @ab14bhardwaj 
> CO-775 Added dealy for messages from bot [MASTER]

- server/config/config-env.js
-> disable sentry on widget v1
->
->
->
> Disable sentry on widget v1 [branch: v1Prod-4.7]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
-> Tested by starting a conversation after the agent's image is removed and also when a new image is set.
-> Issue is explained via the screenshots given below.
> CO-804 Fixed image on Top Bar will be similar to the image visible in message sent by agent.

- server/config/config-env.js
-> create a new project for chat widget test env
-> new errors are catching into chat-widget-test-v2
sample 
->
->
> sentry project change for test env

- webplugin/js/app/mck-sidebox-1.0.js
> CO-775 fixed multiple typing indicators visible if bot message delay is enabled

- webplugin/js/app/mck-sidebox-1.0.js
> CO-775 Delay in Messages from Bot will now comw from appSettings API

- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-ringtone-service.js
- webplugin/js/app/mck-sidebox-1.0.js
-> Added sound notification when the pre-chat pop-up notification appears on the chat widget.
-> By passing `popup: true` in `chatWidget` object inside the appSettings API. And also setting a message in `chatPopupMessage`.
-> Howler audio library for web.
> CO-800 added sound notification whe pre chat popup notification appears

- webplugin/js/app/mck-sidebox-1.0.js
->
->
->
-> https://sentry.io/organizations/applozic/issues/1240204675/?project=1729405&referrer=alert_email
> Sentry bug fix for classList of null

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
-> Fix bug where in case of startConversation placed in onInit, all messages were not loading.
-> By creating a conversation using startConversation via onInit.
> Fix bug where in case of startConversation placed in onInit, all messages were not loading.

- webplugin/plugin.js
-> fix: sentry is undefined
->
->
-> ![Screen Shot 2019-09-25 at 1 56 29 PM](https://user-images.githubusercontent.com/34020392/65583654-3eeba180-df9d-11e9-83e5-1b1d0c75f7d3.png)
> fix: sentry is undefined

- webplugin/plugin.js
-> type check for KommunicateGlobal
-> 1.plugin is getting loaded
2. load the plugin and logout then run the script without reloading the page, no errors are throwing
->
->
> type check for KommunicateGlobal

- webplugin/js/app/mck-sidebox-1.0.js
-> Bug fixes in red text warning.
->
->
->
> Fix the bug where red text breaks on inserting spaces in between

- server/config/config-env.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/pluginOptimizer.js
- webplugin/template/mck-sidebox.html
-> Fix some bugs related to red text display
->
->
->
> recommit previous changes and fix bugs for redtext warning

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
>  Updating bots language code dynamically 

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/plugin.js
-> Avoid XSS attack when someone saving the pre-chat popup message from the dashboard.
-> By saving any message with proper HTML Tags and Javascript inside it as well
> CO-801 Avoiding XSS attack in pre-chat popup message in chat widget

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix the bug when the code was breaking when something was pasted in the text field.
->
->
->
> fix the paste issue in red text warning for the character limit

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/pluginOptimizer.js
- webplugin/template/mck-sidebox.html
> - Load JS code which is not necessary to get executed at the time of initialization.
> - Remove video call related code.
> - Use terser instead of uglify-es as it is no longer maintained and terser is a fork of uglify-es itself.
> - Load Emoji file when emojiLibrary is true.
-> By creating a build and running the sidebox. 
Result :
- Reduction in file size.
- Increase in load speed.
-> https://github.com/terser/terser
> Load JS code afterwards which is not needed in initialization and remove unused code.

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
-> By clicking on the "Start New Conversation" button and clicking the back button as soon as the typing indicator of the bot is visible.
-> Fixed an issue where the typing indicator was visible in case of bot-message delay when switching the conversation or clicking on the FAQ button.
> Fixed typing indicator visible in case of bot message delay when switching the conversation or clicking on FAQ

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix the bug where warning was still showing on assignee change.
->
->
->
> Fix the bug where char limit warning was still appearing on assignee change

- webplugin/pluginOptimizer.js
-> Change the css minify level to skip minifying animation tags. 
->
->
->
> css minify anim fix

- webplugin/js/app/mck-sidebox-1.0.js
-> Enable send button back when assignee is changed from a dialogflow bot to a human agent.
->
->
->
> enable send button on assignee change to human

- webplugin/js/app/mck-sidebox-1.0.js
->new conversation fix and disable bug
->
->
->
> new conversation fix and disable bug

- webplugin/js/app/mck-app.js
->track the URL of the error
-> 
->
->
> sentry : track the url of the error

- webplugin/css/app/mck-sidebox-1.0.css
> Fix pre-chat popup CSS issue with box shadow

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix bug where messageTriggerTimeout and openConversationOnNewMessage are not working.
-> By running script withe below parameters : 
"msgTriggerTimeout":2000,
"openConversationOnNewMessage":true,
-> Events were not getting subscribed due to which error arrowsed.
> Fix bug where messageTriggerTimeout and openConversationOnNewMessage are not working.

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix bug where messageTriggerTimeout and openConversationOnNewMessage are not working.
-> By running script withe below parameters : 
"msgTriggerTimeout":2000,
"openConversationOnNewMessage":true,
-> Events were not getting subscribed due to which error arrowsed.
> Fix bug where messageTriggerTimeout and openConversationOnNewMessage are not working. [Development]

- webplugin/js/app/kommunicate-ui.js
-> The chat popup notification sound will only play once per user per session.
-> If the session is cleared or the existing user logs out then the sound will be played once for the new user.
-> By loading the chat widget. And then refresh the page again and again.
-> By performing `Kommunicate.logout()` and reloading the chat widget with a new user.
> Popup sound will only play once per user.

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix the bug where contact.metadata was coming as null in some cases
> fix bug when metadata is missing in contact object

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
-> By enabling and disabling `popupWidget` value to true or false.
-> By testing with a new account where FAQs are not added or enabled.
-> Fixed an issue where the Width of the Conversation title was fixed irrespective of whether or not FAQ and Close buttons are visible on the widget or not.
> CO-829 Conversation Title width adjustment

- webplugin/js/app/mck-app.js
- webplugin/plugin.js
- webplugin/pluginOptimizer.js
> - Remove unused code.
> - Combine all JS files to one.
> - Removed googleApiKey getting added twice.
> - Add jquery from Kommunicate.app file.
> - By running the script and checking everything is working fine or not.
> Remove unused code, combine all JS files to one and removed googleApiKey getting added twice.

- webplugin/js/app/mck-sidebox-1.0.js
-> Fix CSAT rating now showing up in case of missing tabId in **CURRENT_GROUP_DATA** object.
> fix CSAT not showing up in new conversations

- webplugin/css/app/mck-sidebox-1.0.css
#148 # How was the code tested?
-> By creating a new conversation in sidebox by clicking on the "Start New Conversation" button.
-> Refer screenshots:
> CO-829 Fixed CSS issue related to conversation Title Width adjustment

- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
-> Moved Subscribe events and automatic chat open on refresh code inside onInitApp from postPluginInitialization.
-> The code was reverted in production because of customer-facing an issue while using msgTriggerTimeout and openConversationOnNewMessage. The error was coming because events were not getting published. Verified that it is working after these changes.
-> Don't move the code without knowing what's inside that.
> Code improvements for decrease load time.

- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
-> Chat widget title limitation - implementation
-> Fix bug in CSAT rating.
> RELEASE 5.2.1

- webplugin/build/test.txt
- webplugin/js/app/mck-sidebox-1.0.js
->  update away message on assignee change and remove duplicate code
-> open chat widget, initiate chat with bot, then click on 'talk to human' so that bot to human handoff happens. Tested in both cases when the agent was online and when agent was offline. Away message gets updated on assignment to human agent in case of agent being offline.
->
->
> FW-365 update away message on assignee change

- webplugin/css/app/mck-sidebox-1.0.css
> CO-829 Fix conversation title in mobile view

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
-> Hide iframe on login failure and minor code simplification.
-> kommunicate-hide-custom-iframe class will be added on Iframe in case of login failure to hide it.
> CO-811 Hide iframe on login failure and minor code simplification.

- webplugin/js/app/mck-app.js
- webplugin/js/app/media/media-dom-event-listener.js
-> Fix voice input not working.
-> Error came due to the concatenation of all multiple JS files to a single one.
The event listener was not getting attached because the JS file is adding the HTML to the dom. So the code was getting executed before the element was present in the DOM.
> Fix voice input not working

- webplugin/js/app/km-rich-text-event-handler.js
-> fix: {url} has been blocked by CORS policy while form submission. not for all url's , zaper webhook is throwing an error.
->  from tested with action URL as zapier webhook, data is submitting to webhook 
->
-> currently we are using  Applozic.ALApiService.ajax() method to make POST request . after replacing this method with javascript XMLHttpRequest, data is submitting all URL's(zapier webhook) without any  CORS policy issue. 
> fix: {url} has been blocked by CORS policy while form submission

- webplugin/js/app/km-richtext-markup-1.0.js
->  support "openLinkInNewTab" option on Generic card
-> by default link button will redirect to the new tab. if  openLinkInNewTab false, the link will open in the same window
->
->
> TD-337 : support "openLinkInNewTab" option on Generic card link button

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
-> fix: template 8 : dialogbox buttons are not working
->
->
-> km-cta-button class is using for triggering submit button method
for quick replies - km-quick-replies class will trigger the corresponding method.
km-cta-button class is removed
> [Dev] fix: template 8 : dialogbox buttons are not working

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
->
->
->
-> km-cta-button class is using for triggering submit button method
for quick replies - km-quick-replies class will trigger the corresponding method.
km-cta-button class is removed
> fix: template 8 : dialogbox buttons are not working

- webplugin/css/app/mck-sidebox-1.0.css
> Fix conversation title breaking on devices with less than 320px resolution

- webplugin/css/app/mck-sidebox-1.0.css
> Fix conversation title breaking on devices with less than 320px resolution [MASTER]

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
->remove dependency of adding super admin in the group
->By verifying Conversation Rules
->
->
> #FW-199 remove dependency of adding super admin in the group

- webplugin/js/app/mck-sidebox-1.0.js
-> Skip encryption in case of fetching bot detail Kommunicate API.
-> By creating the conversation and checking that error is not coming while fetching bot details
-> Encryption was not excluded for API which is not getting encrypted.
> Skip encryption in case of fetching bot detail Kommunicate API.

- webplugin/js/app/mck-sidebox-1.0.js
-> websocket level encryption
-> sending and receiving messages for encrypted app id
->
->
> FW-427 websocket level encryption

- webplugin/js/app/kommunicateCommons.js
- Fix the error that was thrown and CSAT banne not showing up incase the conversation is closed by diaglogflow payload
> fix CSAT ratings failing in caase of Dialogflow close conversation 

- rich-messages-code-sample/dialogflow-fulfillment/buttons-using-custom-payload.js
- rich-messages-code-sample/dialogflow-fulfillment/cards-using-custom-payload.js
- rich-messages-code-sample/dialogflow-fulfillment/cards.js
- rich-messages-code-sample/dialogflow-fulfillment/form-using-custom-payload.js
- rich-messages-code-sample/dialogflow-fulfillment/images-using-custom-payload.js
- rich-messages-code-sample/dialogflow-fulfillment/list-using-custom-payload.js
- rich-messages-code-sample/dialogflow-fulfillment/suggestions.js
- rich-messages-code-sample/readme.md
-> code samples for rich messages using dialogflow fulfillment
->
->
->
> code samples for rich messages using dialogflow fulfillment

- server/README.md
-> Create a readme for web-SDK server deployment for customers.
> Create readme for web-SDK server deployment for customers.

- webplugin/js/app/mck-app.js
-> Added option to enable or disable pseudonyms option from the dashboard based on the `pseudonymEnabled` property coming in the chatWidget object in appSettings API.
-> By enabling and disabling pseudonyms option from dashboard. 
->
->
> CO-861 added option to enable or disable pseudonyms

- kommunicate-script-example/README.md
> Updated click event listeners to work with pre-chat popup

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- Make changes to the conversation rating flow as it was confusing to a lot of customers 
- Comments are made optional and its shown that they are
- Rating is no more recorded in 2 parts
------
> update conversation rating flow

- webplugin/js/app/mck-app.js
> Add a check for widgetSettings parameter.
-> Object's key value was getting checked even though the object is null.
> Add a check for widgetSettings parameter.

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
-> Applozic plugin upgrade for sockjs heartbeat suppoort
-> send and receive message real time
->
->
> Sockjs upgrade

- webplugin/js/app/mck-sidebox-1.0.js
-> disable socket debug logs
->
->
->
> FW-511 disable socket debug logs

- webplugin/js/app/mck-sidebox-1.0.js
> Replace MckInitializeChannel with ALSocket code in the KM chat plugin.
> By checking socket functionality in sidebox.
> CO-878 Replace MckInitializeChannel with ALSocket code in KM chat plugin.

- webplugin/plugin.js
-> Fix cross Origin error coming for AWS build files.
-> By running the chat script
> Fix cross Origin error coming for AWS build files.

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
-> Added radio buttons, checkboxes and hidden fields to actionable form in rich messages.
-> This was the custom payload used in dialogflow.
`{ "message": "Submit your details", "platform": "kommunicate", "metadata": { "contentType": "300", "templateId": "12", "payload": [ { "type": "text", "label": "Name", "placeholder": "Enter your name" }, { "type": "radio", "title": "Choose your Favorite band:", "name": "Bands", "options": [ { "label": "Evanescence", "value": "evanescence" }, { "label": "Neutral Milk hotel", "value": "NMH" }, { "label": "The XX", "value": "The XX" }, { "label": "Aquilo", "value": "Aquilo" } ] }, { "type": "checkbox", "title": "Choose your interests:", "name": "Interests", "options": [ { "label": "Coding", "value": "coding" }, { "label": "Crying", "value": "crying" }, …
> Rich message Form template enhancements

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/kommunicate-ui.js
-> fix: error while uploading the image.
-> upload image -> stop upload -> immediately click on re-upload - > no errors are throwing
-> Error is throwing when the user tries to re-upload the image immediately after cancelling the upload. Image upload API is taking time(5sec) to return fileMeta Object.
->
> fix: error while uploading image

- webplugin/js/app/km-utils.js
- webplugin/plugin.js
> Plugin 5.6

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
-> Added render support for all fields in form-template for chat widget.
-> This custom payload was passed from dialogflow.
`{
"message": "Submit your details",
"metadata": {
"payload": [
{
"type": "text",
"label": "Name",
"placeholder": "Enter your name"
},
{
"type": "text",
"label": "Age",
"placeholder": "Enter your age"
},
{
"type": "radio",
"title": "Choose your interests:",
"name": "hobbies",
"options": [
{
"label": "Coding",
"value": "coding"
},
{
"label": "cooking",
"value": "cooking"
},
{
"label": "mining",
"value": "mining"
},
{
"label": "Drinking",
"value": "drinking"
}
]
},
{
"type": "hidden",
"name":"email",
"value": "hardik@kommunicate.io"
},
{
"type": "password",
"label": "password",
"placeholder": "Enter …
> Added render support for all fields in form-template for chat widget.

- webplugin/js/app/mck-sidebox-1.0.js
->  remove sockjs
-> tested in local by sending and receiving message
->
->
> FW-540 remove sockjs

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
-> Added radio buttons, checkboxes and hidden fields to actionable form in rich messages.
-> This was the custom payload used in dialogflow.
`{ "message": "Submit your details", "platform": "kommunicate", "metadata": { "contentType": "300", "templateId": "12", "payload": [ { "type": "text", "label": "Name", "placeholder": "Enter your name" }, { "type": "radio", "title": "Choose your Favorite band:", "name": "Bands", "options": [ { "label": "Evanescence", "value": "evanescence" }, { "label": "Neutral Milk hotel", "value": "NMH" }, { "label": "The XX", "value": "The XX" }, { "label": "Aquilo", "value": "Aquilo" } ] }, { "type": "checkbox", "title": "Choose your interests:", "name": "Interests", "options": [ { "label": "Coding", "value": "coding" }, { "label": "Crying", "value": "crying" }, …
> Add form template enhancements in rich message. [MASTER]

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-ringtone-service.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
> Add mute sound notification feature in Howler.
> Fix bug where the v1 plugin was not even getting loaded with the current codebase.
> By selecting the **no sound** option from chat-widget section in dashboard.
> FW-576 Add mute sound notification feature in Howler.

- webplugin/js/app/mck-app.js
> Update Applozic version to 5.9.1

- webplugin/js/app/mck-app.js
> correct version to 5.9

- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
-> Rich message template 13 implementation
1. Link button
2. Submit button
3. Suggested reply
4. Combining all buttons together 
-> Payload 
`{
"message": "click on the buttons",
"metadata": {
"templateId": "13",
"payload": [
{
"type": "link",
"name": "Go to google",
"action": {
"url": "https://www.google.com",
"openLinkInNewTab": false
}
},
{
"name": "submit button",
"type": "submit",
"action": {
"message": "acknowledge message",
"formData": {
"amount": "1000",
"description": "movie ticket"
},
"formAction": "https://example.com/book",
"requestType": "json",
"replyMetadata": {
"KM_CHAT_CONTEXT": {
"key-1": "value-1"
}
}
}
},
{
"name": "suggested reply 1",
"type": "suggestedReply",
"action": {
"message": "Cool! send me more.", …
> TD-471: Rich message template 13 implementation

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
> Custom welcome message

- webplugin/js/app/mck-sidebox-1.0.js
- Add checkUserConnectedStatus in sidebox.js file as it contains jquery related code.
- This function was moved out of chat.min.js file because it is dependent on Jquery.
-  By running the function moved from chat.min.js ->sidebox.js
> FW-606 Add checkUserConnectedStatus in sidebox.js file as it contains Jquery related code.

- webplugin/js/app/kommunicate.custom.theme.js
- Fix bug where undefined is coming on chat widget icon.
- Already fixed in v2 plugin.
- By running the chat widget.
> Fix bug where undefined is coming on chat widget icon for v1 plugin.

- webplugin/js/app/kommunicate-ui.js
> The user rating is not displaying correctly in the sidebox.
> By resolving the conversation and testing below cases :
> - Emoticons only.
> - Emoticons and comment.
> The user rating element was not getting updated if comments are also added in the feedback.
> FW-665 User rating is not displaying correctly in Sidebox

- webplugin/js/app/mck-sidebox-1.0.js
- Change feedback v1 API to v2 API
- By sending feedback from the plugin and verifying data in user_feedback table
> FW-562 User association in CSAT rating

- server/config/config-env.js
> disable sentry on prod

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
- Add support for updated sound file names.
- Use "subtle" as a default notification tone.
- By changing ringtone from dashboard with new names.
> FW-579 Add support for updated sound file names. [WIDGET]

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/labels/default-labels.js
->  form template validation
->
here is the metadata for form validation
`{
"message": "Form",
"metadata": {
"payload": [
{
"type": "text",
"label": "Name",
"placeholder": "Enter your name",
"validation": {
"regex": "[A-Za-z0-9]",
"errorText": "Field is mandatory"
}
},
{
"type": "number",
"label": "Phone Number",
"placeholder": "Enter your phone number"
},
{
"type": "text",
"label": "Email",
"placeholder": "Enter your email",
"validation": {
"regex": "^(([^<>()\\[\\]\\.;:\\s@\"]+(\\.[^<>()[\\]\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$",
"errorText": "Invalid Email"
}
},
{
"type": "submit",
"label": "Submit",
"requestType": …
> TD-399: form template validation

- webplugin/js/app/km-richtext-markup-1.0.js
-> in the form some fields don't have the label, for example, the hidden input field. so that case code will throw an error.
-> form validation
> keep a check for label

- webplugin/plugin.js
- fix the bug which was causing UI issues in mobile view on iOS devices
- The code was tested on safari's iPhone emulation, by opening the widget on a Squarespace website. 
- The body tag was set as `position: fixed` by our restrictScroll which is not really necessary to disable scroll so got rid of it. 
> fix kommuicate widget UI breaking on squarespace

- webplugin/js/app/mck-sidebox-1.0.js
- Fix bug where openConversationOnNewMessage appOption was not working.
- By passing parameter openConversationOnNewMessage to true;
- The wrong variable was getting passed in onMessageNotification function.
> Fix bug where openConversationOnNewMessage appOption was not working.

- LICENSE
- Add License for Kommunicate-Web-SDK Repository.
- BSD 3-Clause License
> Add License for Kommunicate-Web-SDK Repository.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/template/mck-sidebox.html
- Fix alignment problem happening in the browser when the mobile width is smaller
- Code was tested on multiple screen widths between 320 - 400px
- Fixed widths were causing issues in smaller widths because they aren't responsive.
> FW-584 Fix alignment problem in mobile browsers with smaller width.

- webplugin/js/app/mck-sidebox-1.0.js
->**remove send feedback message code from ui**
->
->
->
> #remove send feedback message code from ui [Merge after server release in prod]

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
Reverts Kommunicate-io/Kommunicate-Web-SDK#393
> Revert "Applying routing rules from backend"

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- In favor of routing rules from the backend, removing admin and users from group creation payload. It will be automatically added by the routing rule process.
> FW-507 Remove admin and user from front end.

- webplugin/css/app/km-rich-message.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
- Add support for moving the chat widget to the bottom left of the screen. 
- Code was tested by sending the following param in the appsettings API 
`{ 
"chatWidget": { 
"moveWidgetToLeft" : true
}
}`
> PD-296 Allow users to place widget on the left corner of the screen.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- Send the attachment in one click
- By sending all types of attachments
> TD-484 Send attachment on one click.

- webplugin/css/app/mck-sidebox-1.0.css
- Fix ellipsis not cming in agent name in chat widget
> fix ellipsis in chatwidget

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
->remove old widgetTheme key from app setting
->
->
->
> FW-507 remove old widgetTheme key from app setting

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/pluginOptimizer.js
- Disconnect socket for a user with no conversation after n minutes. (n: 4 minutes)
- Fix bug where notification is not getting shown.
- Beautify code. (Ignore pluginOptimizer.js completely.
- Don't disconnect in the case of msgTriggerTimeout.
- By checking that socket is getting disconnected and reconnected when someone clicks on the widget.
- Notification is not getting shown because of some recent changes.
- Reason: Code which was increasing width of iframe was commented.
> FW-430 Disconnect socket for user with no conversation after n minutes.

- webplugin/js/app/km-message-markup-1.0.js
-> show download link only for video and audio
-> download link showing only for audio, video and attachment v1 types 
> show download link only for video and audio

- webplugin/js/app/km-message-markup-1.0.js
-> fix: location sharing is not working
-> ![Screen Shot 2020-03-04 at 2 23 16 PM](https://user-images.githubusercontent.com/34020392/75861663-ba426080-5e23-11ea-9793-fd93ecb62dc0.png)
->
->
> fix: location sharing is not working

- webplugin/css/app/km-rich-message.css
-> bug:  rich message  button design is broken
-> link button tested, design and functionality working
> fix: rich message button design

- webplugin/js/app/mck-app.js
- webplugin/plugin.js
- Add alt attribute for IMG tag and add a missing semicolon.
- By running the script and checking that the build process is working fine or not.
> Add alt attribute for IMG tag and add missing semicolon.

- server/config/config-env.js
- Update bot platform URL.
- Older: "https://bots-test.applozic.com"
- New: "https://bots-test.kommunicate.io"
> Update bot platform URL.

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/mck-sidebox-1.0.js
- Whenever someone was clicking on a suggested reply the keyboard would popup leading to disruption, so disabled the behavior.
> disable keyboard popup when a user click on suggestion chips

- webplugin/js/app/mck-sidebox-1.0.js
- Remove human handoff check while using 256 characters feature.
- By checking that 256 characters issue is working if bot human handoff is enabled from the Dashboard.
> Remove human handoff check while using 256 characters feature.

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
- Jquery URL: https://cdn.kommunicate.io/kommunicate/jquery.3.2.1.min.js.
- By loading the chat plugin and checking everything is working fine or not.
> FW-766 Use jquery file from Kommunicate CDN.

- webplugin/plugin.js
- Update jquery version and use proper naming convention in URL.
- URL: https://cdn.kommunicate.io/kommunicate/jquery-3.4.1.min.js
> Update jQuery version and use proper naming convention in URL.

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Connect to the socket on widget click by passing an appOption.
- appOption: connectSocketOnWidgetClick
example: "connectSocketOnWidgetClick": true
- By clicking on widget and checking widget is working fine or not.
> Connect to socket on widget click by passing an appOption.

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Connect to the socket if the user has conversations in the case of connectSocketOnWidgetClick is true.
- Improve ternary check-in mck-app.js file.
- By checking if the user has a conversation and socket should connect initially.
- In case of user has a conversation socket should get connected initially independent of any condition.
> Connect to the socket if the user has conversations in the case of connectSocketOnWidgetClick is true.

- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- Don't connect socket for trial applications.
- By checking for application with the trial plan and with non-trial plans.
> Don't connect socket for trial applications.

- webplugin/js/app/mck-sidebox-1.0.js
- Add a for widget settings in case of checking for notificationVolume key from widget settings object.
- By checking that widget is working fine when widget settings object is null.
> Add a for widget settings in case of checking for notificationVolume key from widget settings object.

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-message-markup-1.0.js
-> fix: attachment not able to download
-> send an attachment from the dashboard to plugin and plugin to dashboard, both the case's attachment download is working
> fix: attachment not able to download

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
-> Add support to disable CSAT button once the rating is submitted to avoid multiple clicks.
> Disable CSAT button once the rating is submitted.

- .github/workflows/stale.yml
- Setup "Mark stale issues and pull requests" for Kommunicate-Web-SDK
- https://github.com/actions/starter-workflows/blob/master/automation/stale.yml
> Setup "Mark stale issues and pull requests" for Kommunicate-Web-SDK

- webplugin/js/app/mck-sidebox-1.0.js
-> The error for required text field was only displayed as a border around middle part of the text box, so changed that to make the error cover the entire container of the text box.
->
> Fix the issue where the required text field error is not displayed around the whole text box.

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
- Improve alt tag content in the IMG tag.
- By checking the content of the IMG tag in the browser.
> Improve alt tag content in IMG tag.

- package.json
- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/knowledgebase/kb.js
- webplugin/pluginOptimizer.js
- Removed helpdocs code from the plugin.
- Added nodemon for development which will restart the server on save.
- Update minify plugin version and code as per there new documentation.
- By checking the plugin is working fine.
- Files getting minified are working fine or not.
- The server is restarting or not.
- FAQ's are getting loaded or not.
- [Nodemon](https://www.npmjs.com/package/nodemon)
> Remove helpdocs code, add nodemon and update minify package and code.

- package.json
- webplugin/js/app/mck-sidebox-1.0.js
- Fix bug where the message is not rendering when KM_ASSIGN_TO metadata is coming and bump minimist package version.
> Fix bug where message is not rendering when KM_ASSIGN_TO metadata is coming and bump minimist version.

- .github/workflows/stale.yml
- Update stale and close days in PR GitHub actions
> Update stale and close days in PR github actions

- .github/pull_request_template.md
- Added a checklist in the PR template.
- How to use a checklist in markdown.
> Add checklist in PR template.

- webplugin/js/app/kommunicateCommons.js
- Fix bug wherein case of socket connects on widget click.
- Socket connect on widget click.
- Socket disconnect logic is working fine or not.
> Fix bug where in case of socket connect on widget click.

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- Fix bug wherein case of socket connects on widget click.
> Fix bug wherein case of socket connects on widget click.

- webplugin/js/app/km-utils.js
- fix: data is not getting stored into the browser cookie
- tested in this website https://comtele.com.br/ - new user is not getting created everytime
- When I add "domainKey": "bl" on kommunicateSettings, end-users are same for react.balushome.com and balushome.com websites
- When storing data into cookie we are passing "com.br" as a domain in the cookie URL(document.cookie)
-fix found from here: http://jsfiddle.net/zEwsP/4/
> TD-826: fix - data is not getting stored into the browser cookie for some websites.

- webplugin/js/app/km-utils.js
- fix: data is not getting stored into the browser cookie
- tested in this website https://comtele.com.br/ - new user is not getting created everytime
- When I add "domainKey": "bl" on kommunicateSettings, end-users are same for react.balushome.com and balushome.com websites
- When storing data into cookie we are passing "com.br" as a domain in the cookie URL(document.cookie)
-fix found from here: http://rossscrivener.co.uk/blog/javascript-get-domain-exclude-subdomain
http://jsfiddle.net/zEwsP/4/
> [Release] fix: data is not getting stored into the browser cookie

- README.md
Kommunicate demo and documentation link added
-
-
-
-
> Product demo and documentation link

- webplugin/js/app/km-utils.js
->Added samesite param exclusively for chrome to hide the warning coming for samesite.
> Remove warning coming in chrome for samesite

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- Add aria-label for the pre-lead collection template.
- By checking that area-label is getting added or not.
- Check with Mac VoiceOver.
> Add aria-label for pre-lead collection template.

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
- webplugin/template/mck-sidebox.html
- Add a title label for the heading of Pre-Chat Lead collection.
- Add aria-label for the pre-lead collection template. 
- Add content in an iframe.
- By the QA team.
> Add label and improve accessibility support in widget.

- webplugin/js/app/km-richtext-markup-1.0.js
- rich message form new format payload support
- The form template is loading for new and old format payloads 
new payload is 
`{
"message": "Form V2",
"metadata": {
"payload": [
{
"type": "text",
"data": {
"label": "Name",
"placeholder": "Enter your name"
}
},
{
"data": {
"placeholder": "Enter Password",
"label": "Password"
},
"type": "password"
},
{
"data": {
"placeholder": "Enter your Email ID",
"label": "emailId",
"validation": {
"regex": "^(([^<>()\\[\\]\\.;:\\s@\"]+(\\.[^<>()[\\]\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$",
"errorText": "Invalid Email"
}
},
"type": "text"
},
{
"data": {
"label": "employee Type",
"placeholder": "Enter …
> FW-1241: rich message form new format payload support

- webplugin/js/app/km-richtext-markup-1.0.js
- remove arrow function.
- form is loading on chat widget 
- arrow function is not supported in IE 
> form is not loading in IE

- webplugin/template/mck-sidebox.html
- add old class back as some customers might be using it in their custom code.
> revert classname removal

- webplugin/template/mck-sidebox.html
> Revert classname removal. [MASTER]

- webplugin/pluginOptimizer.js
- Update CSS minifier attributes.
- By checking bot issue is fixed or not.
> Update CSS minifier attributes.

- webplugin/pluginOptimizer.js
- Update css minifier attributes. [Master]
> Update css minifier attributes. [Master]

- webplugin/pluginOptimizer.js
> Set CSS minfier level to 1.

- webplugin/plugin.js
- Upgrade to the new jQuery version.
- Add the new version file in Kommunicate CDN.
- Use the CDN link for internal use.
- Reason to upgrade to new version of jQuery: https://snyk.io/vuln/npm:jquery@3.4.1
- By checking everything is working fine and no jquery related code is breaking because of the version upgrade.
> TD-919 Upgrade to new jQuery version.

- example/Page_load.html
> Open chat widget on page load 

- example/Set-height-width-for-chatwidget.html
> Set height and width for Chat widget example

- webplugin/js/app/kommunicate-ui.js
Clone PR of : https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/500
> Add support to convert urls in away message to anchor tag[RELEASE]

- webplugin/css/app/km-sidebox.css
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- No internet connection message in sidebox
-
-
-
> No internet connection message in sidebox

- webplugin/js/app/mck-sidebox-1.0.js
- Change poweredBy URL.
- New URL: https://www.kommunicate.io/poweredby
- By checking that on click of powered by it's getting redirected to the new URL.
> Change poweredBy URL.

- webplugin/css/app/mck-sidebox-1.0.css
Refer: https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/517
> Fix prod bug where message typing box is getting disappeared. [MASTER]

- webplugin/css/app/mck-sidebox-1.0.css
- Fix prod bug where message typing box is getting disappeared.
- By checking that issues are fixed or not.
- The bug might due to recent chrome updates.
> Fix prod bug where message typing box is getting disappeared.

- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
-
- tried to send and download the different attachments including java file
- java file doesn't have file type/media type so it's breaking.
> fix: java file not able sent as an attachment

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- develop dropdown on the form template
payload:
`{
"metadata": {
"payload": [
{
"type": "dropdown",
"data": {
"title": "Cars",
"name": "cars",
"options": [
{
"value": "volvo",
"selected": true,
"label": "Volvo"
},
{
"label": "Saab",
"value": "saab"
},
{
"value": "mercedes",
"label": "Mercedes"
},
{
"label": "Audi",
"value": "audi"
}
]
}
},
{
"data": {
"errorText": "Please select your profession",
"options": [
{
"value": "eng",
"label": "Engineer"
},
{
"value": "ent",
"label": "Entrepreneur"
},
{
"value": "dc",
"label": "Doctor"
},
{
"label": "Lawyer",
"value": "lawyer"
},
{
"label": "select",
"disabled": true,
"selected": true
}
],
"title": "Your profession",
"name": "profession"
},
"type": "dropdown"
},
{
"data": {
"placeholder": "Enter your name",
"label": "Name"
},
"type": "text"
},
{ …
> FW-1296 Dropdown in rich message form template

- webplugin/js/app/mck-ringtone-service.js
- webplugin/js/app/mck-sidebox-1.0.js
-Add option to disable sound in sidebox greeting message
-
-
-
> FW-1308 Add option to disable sound in sidebox greeting message

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
textarea support on rich message form.
-
- payload
`{
"message": "Form V2",
"metadata": {
"payload": [
{
"type": "textarea",
"data": {
"rows": 4,
"cols": 10,
"name": "review",
"placeholder": "Describe yourself here...",
"title": "Review of Kommunicate"
}
},
{
"type": "text",
"data": {
"placeholder": "Enter your name",
"label": "Name"
}
},
{
"data": {
"type": "submit",
"action": {
"message": "optional- this message will be used as acknowledgement text when user clicks the button",
"formAction": "https://reqres.in/api/users"
},
"name": "Submit"
},
"type": "submit"
}
],
"contentType": "300"
},
"platform": "kommunicate"
}`
> FW-1344: form textarea support

- webplugin/js/app/km-richtext-markup-1.0.js
- moved errorText inside validation object
- validation is working for dropdown
> move errorText inside validation object in the form dropdown payload 

- webplugin/css/app/km-rich-message.css
- resize option for textarea
- Textarea able resize vertically 
> resize option for textarea

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
- Rich message for the video
- payload :
`{
"metadata": {
"payload": [
{
"url": "https://s3-migration-dot-applozic.appspot.com/rest/ws/aws/file/AMIfv95BPKLnhNtiYz0SNJYXTDhUkvhPYQikSjFaoL1hbg1zCcK8n6KZZfZC5Z42bfxOLaNeKSbKrt4o9pI0_ICb1fKKY8HqtcCeEuUZU8b18u8sr-4U5d4rFtmC79cn_0xaiV0MQfF01T0hAea8sQANoaYuvR5hQJHiFSB047yp1mkfqcwNb_ExaX1xutdJ8Qamkjp8xTKjlPiG0920T7qqLFIBxl1eGL7ikvTCtXG_f8Me8OKsEOhUXOP7LLuJLcOG_p8cijsp",
"caption": "caption for video 1",
"width": "300px"
},
{
"source": "youtube",
"url": "https://www.youtube.com/embed/3-ijFzzF934"
}
],
"templateId": "14"
},
"message": "hello this is test video",
"platform": "kommunicate"
}`
- tested with a youtube video and other
video links
> FW 1330 Rich message for the video

- webplugin/js/app/mck-sidebox-1.0.js
-> Fixed the bugs where Conversation header was displayed with agent/bot name in FAQ tab when pressing back button or on status change.
> Fix the widget top bar failing when going to faq tab and pressing back button.

- webplugin/js/app/km-message-markup-1.0.js
- fix: location share is not working
- Tested location share from the dashboard to widget and widget to the dashboard 
- Tested image, audio, video, PDF, java attachments.
- location share :
-Other Attachments :
> fix: location share is not working

- webplugin/js/app/km-message-markup-1.0.js
> [plugin-6.3] location share is not working

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
> Revert "FW 1376 support for teamId"

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- PR ref to master: https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/537
-
-
-
> [Development] FW 1376 support for teamId 

- webplugin/js/app/mck-sidebox-1.0.js
>Related Dashboard PR: https://github.com/AppLozic/Kommunicate/pull/6774/files
- hide empty msg box from msg list
Before:
After:
----------------------------------
Before:
After:
> hide empty msg box from msg list 

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-app.js
- Allow the chat widget to work on kommunicate.io domain even if domain restriction is enabled or chat widget is disabled. 
-
-
-
> Allow chat widget to work on kommunicate.io

- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
- Exclude "assigned to", "marked as spam" messages in converting to speech
- Load the widget with voiceOutput: true. Check the incoming messages
-
-
> Don't convert status and assign messages to speech

- webplugin/js/app/kommunicate-ui.js
- It was requested by a lot of customers that they needed to dissable the greeting message in the mobile devices, this option adds the facility for that
TE: Make sure you're comparing your branch with the correct base branch
> add option to hide the greeting message in mobile devices

- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- Fix XSS attack via display name of agent/bot set from the dashboard.
- Fix UI issue coming in case of someone add HTML in the display name of agent/bot.
- Prevent XSS attack via FAQ name and description.
- Beautify code.
- By adding below script as the name for agent/bot from our dashboard.
> <script>alert("hello");</script> 
- By adding the above script in FAQ name and description from FAQ-create section in dashboard.
- Previously script was getting executed after the fix script is not getting executed.
- Fix UI issue coming in case of someone add HTML in the display name of agent/bot.
> TD-1187 Fix XSS attack via display name of agent/bot set from the dashboard and via FAQ.

- webplugin/js/app/kommunicate-ui.js
- webplugin/lib/js/jquery.linkify.js
- webplugin/pluginOptimizer.js
- Fix XSS attack via away message.
- Update jQuery linkify library we're using.
- We were previously using the minified version of the same library.
- Previously we had made the changes in jQuery-linkify minified code itself.
- So to make things more understandable, we're now using un-minified code picked from the library and have added the changes to it which were previously done by our team. We're now minifying the file using our code.
- Removed "mck-ui-plugins.min.js" file from the minification process as it jQuery-linkify code only. Created a new file with name specific to the library to make things simple for others in future.
_Library Details:_ 
> -  https://github.com/uudashr/jquery-linkify
> - Version: https://github.com/uudashr/jquery-linkify/blob/9053e5a7184e3532c65908c3337c64066 …
> TD-1187 Fix XSS attack via away message and update jQuery linkify library we're using.

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
-Waiting Queue Real time update
-
-
-
> Waiting Queue Real time update

- webplugin/js/app/mck-app.js
> Change to var for IE 6-10

- webplugin/js/app/mck-app.js
> remove arrow function

- webplugin/js/app/media/media-service.js
- Fix bug SpeechSynthesisUtterance is not supported. [IE]
> Fix bug SpeechSynthesisUtterance is not supported. [IE]

- webplugin/js/app/mck-sidebox-1.0.js
-remove waiting list call from scroll
-
-
-
> remove waiting list call from scroll

- webplugin/js/app/mck-sidebox-1.0.js
- fix: not able to send an attachment
- fix: image icon is not showing in the contact list(while sending image from the dashboard to widget)
-
-
-
> fix: not able to send attachment

- webplugin/js/app/mck-sidebox-1.0.js
> if check correction

- webplugin/css/app/km-rich-message.css
- set min-width for rich message video player
> set min-width for rich message video player

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- send form data back in chat
- **password and hidden field values are not sending back on chat**.
- newly added property:
`{
"data": {
"action": {
...,
"postBackToKommunicate": true
},
"type": "submit",
"name": "Submit"
},`
- sample form payload
`{
"metadata": {
"payload": [
{
"data": {
"label": "Name",
"placeholder": "Enter your name"
},
"type": "text"
},
{
"type": "password",
"data": {
"placeholder": "Enter your password",
"label": "Password"
}
},
{
"type": "hidden",
"data": {
"value": "some_secret_detail",
"name": "userDetail"
}
},
{
"data": {
"options": [
{
"label": "Male",
"value": "male"
},
{
"label": "Female",
"value": "female"
},
{
"value": "other",
"label": "Other"
}
],
"name": "Gender",
"title": "What do you identify as:"
},
"type": "radio"
},
{
"type": …
> FW-1463: send form data back in chat

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
Reverts Kommunicate-io/Kommunicate-Web-SDK#574
> Revert "remove default agent id from create conversation payload"

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
- Allow to upload files with html in their names. While rendering it in the UI, escape the HTML so it shown normally and not rendered as HTML.
- Upload a file named `<h1> test <h1>.txt` and `<h1> test <h1>.png`.
- Check that they are uploaded normally
- HTML should not be rendered
-
-
> Allow file upload with html in their name and Escape the HTML tags when showing in UI

- webplugin/js/app/km-rich-text-event-handler.js
- fix: error is throwing with submit button
- submit button and link button templates are working.
- form postBackToKommunicate is working
-
-
> fix: error is throwing with submit button

- webplugin/css/app/km-rich-message.css
- set min-width and max-width for video templates
- if user width is "10000px" , video templates is not breaking.
> set min-width and max-width for video templates

- server/config/config-env.js
- Add widget-enterprise config.
> Add widget-enterprise config.

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- add an option in settings for removing attachment from the widget
- PR: https://github.com/Kommunicate-io/Kommunicate-Dashboard/pull/79
attachment parameter in widget is changed
-
-
> Remove attachment option under settings 

- server/config/config-env.js
- Add prod enterprise in the config file.
> Add prod enterprise in the config file.

- server/config/config-env.js
- Update server URL for enterprise config.
> Update server URL for enterprise config.

- webplugin/js/app/mck-app.js
-add attachment setting support in plugin
-
-
-
> add attachment setting support in plugin

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
-Changes for waiting queue new flow . In new flow conversation will go in waiting queue when user will send message.
-
-
-
> Changes for waiting queue new flow

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- ref: #537
- ref: https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/537
-
-
> Team assignment

- webplugin/js/app/kommunicate.js
- webplugin/js/app/media/media-service.js
- webplugin/js/app/media/typing-area-dom-service.js
- Session storage is unavailable in third-party iframe in Incognito mode by default.
- Use `applozic._globals` for voiceOutput and voiceInput
- 
-
-
> Session storage unavailable in third-party incognito environment

- webplugin/js/app/mck-sidebox-1.0.js
- To fix the bug where the  custom payload for the HTML rich message was not rendering as HTML, instead it was rendering as plain text
- Branch development
-
-
> TD-1463 HTML template for bot replies not working.

- kommunicate-script-example/README.md
- Fix an error where the script was not running.
-
-
-
> added a check in forEach loop

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/597
> updated http to https for location

- webplugin/js/app/kommunicate-ui.js
> CSAT rating remains highlighted [VOGO  priority #3]

- webplugin/js/app/mck-sidebox-1.0.js
> added hide FAQ logic

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
-Remove waiting queue count
-
-
-
> Remove waiting queue count

- webplugin/css/app/km-rich-message.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/609
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/618
> TD-1514 Hide List and button in a rich message on click

- webplugin/css/app/km-rich-message.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/621
> TD-1514 Hide List and button in a rich message on click [PLUGIN 6.5]

- webplugin/js/app/kommunicate-ui.js
- Dynamically set the height of the widget iframe when popup message was shown.
- Configure a popup greeting message in dashboard.
- Load chat widget in test page.
- when the popup greeting comes, right click and inspect element. 
- The height of the iframe containing the widget should be adjusted according to message.
-
-
> TD-1534 Chat widget div blocking website clicks

- webplugin/js/app/media/media-service.js
- Excluding HTML messages for text-to-speech
-
-
-
> Consider only text messages for Text-to-Speech

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/media/media-service.js
- Fix the issue where the chat widget was not loading in the IE.
- get the branch deployed on widget-test
- load the script in IE
-
- backticks and arrow functions were used in the code which was throwing error in ie
> Chat widget was not loading in the IE

- .husky/pre-commit
- webplugin/css/app/km-rich-message.css
-Make the font-size for all the buttons same in the chat widget
- Add some buttons to your intent using Kompose-Bot Builder.
- Check the font size for all buttons.
-
-
> Fw-1965-Keep the font-size for all the buttons same in chat widget

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
> [Release] FW 1891

- server/config/config-env.js
- Add a new env widget-beta for testing purposes
-
-
-
> Added BETA in env config

- webplugin/js/app/mck-sidebox-1.0.js
- To tackle the use case of cards as horizontal image list and horizontal text list.
- payload 1 - horizontal list of images
- `{
"message": "Carousel",
"metadata": {
"templateId": "10",
"payload": [
{"header": {
"imgSrc": "https://picsum.photos/300"
}},{"header": {
"imgSrc": "https://picsum.photos/300"
}},{"header": {
"imgSrc": "https://picsum.photos/300"
}},{"header": {
"imgSrc": "https://picsum.photos/300"
}}
]
}
}
`
- payload 2 - horizontal list of text
- `{
"message": "Carousel",
"metadata": {
"templateId": "10",
"payload": [
{
"title": "KA-05-AJ-6293"
},
{
"title": "KA-51-AD-3940"
},
{
"title": "KA-51-AE-0261"
},
{
"title": "KA-03-AH-3520"
},
{
"title": "KA-05-AK-2178"
}
]
}
}`
-
- …
> FW-2055 If hidePostCTA is enabled, it should not hide cards not having CTA buttons

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/648
> FW-2055 If hidePostCTA is enabled, it should not hide cards not having CTA buttons 

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- make conversations in waiting queue distinguishable
- In conversation
- in conversation list
-
-
> FW-2056 Unassigned Waiting Queue Conversations should show 'Waiting Queue...' in header

- webplugin/js/app/mck-sidebox-1.0.js
- the message should not disappear if it is initial message and is not interacted
- create a welcome intent having button
- turn on hidePostCTA in widget
- create a new conversation
- then go back and return to conversation, the buttons should not disappear 
-
-
> hidePostCTA issue

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/651
> hidePostCTA issue [PLUGIN-6.6]

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- create/open conversation using clientGroupId
- if a conversation is not already created then it will create a new conversation with `clientGroupId`.
- if the conversation already exists with `clientGroupId` then it will open the existing conversation.
- use the following API to create or open conversation by `clientGroupId`.
```JS 
var conversationDetail = {
"clientGroupId": unique id 
}
Kommunicate.startConversation(conversationDetail, function (response) {
console.log("new conversation created", response);
});
```
- This is requested by the Vakil Search.
> create/open conversation using clientGroupId

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
**- Remove confusion on kommunicate and Kommunicate in the web chat plugin.**
- **Run Kommunicate script in the console and check for properties of both objects (Kommunicate and kommunicate).**
---
-
-
> FW 2013 Confusion on kommunicate and Kommunicate in web chat plugin 

- webplugin/js/app/mck-sidebox-1.0.js
> Replace forEach to map for nodelist

- webplugin/js/app/media/media-service.js
> Bot voice release

- webplugin/js/app/media/media-service.js
- Add support for the multi-platform bot voice.
- Enable voice output and add an array of bot voice name in `voiceName` property in `appSettings`.
```
(function (d, m) {
var kommunicateSettings = {
appId: "8ced8a81108c654234a393115cc2ea4f",
popupWidget: true,
automaticChatOpenOnNavigation: true,
voiceOutput: true,
voiceName: [
"Google हिन्दी",
"Google UK English Male",
"Google US English",
], // Replace Google Deutsch with the voiceName from the below mentioned table list
voiceRate: 1,
};
var s = document.createElement("script");
s.type = "text/javascript";
s.async = true;
var h = document.getElementsByTagName("head")[0];
h.appendChild(s);
window.kommunicate = m;
m._globals = kommunicateSettings;
})(document, window.kommunicate || {}); …
```
> FW-2100 Bot voice improvement [Add multi-platform bot voice]

- webplugin/js/app/media/media-service.js
> Fw 2100 release

- webplugin/js/app/mck-sidebox-1.0.js
- to fix the bug related to lazyImages
- open any conversation 
- try to upload images
-
-
> FW-2217 Fix for the lazyImages.map is not a function error

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/674
> fix for the case where the outline was comming for list rich message in hidePostCTA [DEVELOPMENT]

- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- Setting to restrict CSAT to just once, is fixed by adding the oneTimeRating flag in kommunicateSettings object
- [] I have compared it with mocks and all design elements are the same.
- In script add the `oneTimeRating : true` flag into the kommunicateSettings object for one time CSAT rating
- For multiple time CAST rating remove the line `oneTimeRating : true`  or change it to the `oneTimeRating : false` in  kommunicateSettings object
- result of one time rating the conversation 
-
-
> FW-2131 Setting to restrict CSAT to just once

- webplugin/js/app/kommunicate.js
> FW-2259 Fix group metadata is not showing on startConversation

- kommunicate-script-example/README.md
> Script tag and  Kommunicate spelling corrected

- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/mck-sidebox-1.0.js
> fix for dialogflow quickreplies in hidePostCTA [release-9.3]

- webplugin/template/mck-sidebox.html
> fix for waitingqueue bug [release-9.3]

- webplugin/js/app/mck-sidebox-1.0.js
-
- **use installation script and check for the API details in network panel**
---
---
-
-
> FW-2276 Use KM API URL for bot detail | web plugin

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/mck-sidebox-1.0.js
- Wanted to change the chat widget icon shape to a square by adding a parameter in widget settings.
- Made the code changes and tested the same by updating Kommunicate settings in the script.
- `Note:` The image you are using for the icon needs to be in a square avatar 
`(function(d, m){
var kommunicateSettings = 
{"appId":"307ec0c522a953b521d67a195c64ade3","popupWidget":true,"automaticChatOpenOnNavigation":true,"iconShape":"square"};
var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
var h = document.getElementsByTagName("head")[0]; h.appendChild(s);
window.kommunicate = m; m._globals = kommunicateSettings;
})(document, window.kommunicate || {});`
---
---
- Creating variables with kommunicate._globals …
> FW-1976 Chat widget setting for square icon

- webplugin/css/app/km-login-model.css
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
-
- **Make sure pre-chat lead is enabled for your APP_ID.**
https://user-images.githubusercontent.com/22856546/121477733-d7ca8680-c9e5-11eb-81bf-482beda4a82a.mov
-
-
> Fw-2201 Throwing 401 in chat widget plugin, when pre chat lead collection feature is enabled and submitting the details.

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/684
> fix for dialogflow quickreplies in hidePostCTA [dev]

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/684
> fix for dialogflow quickreplies in hidePostCTA [master]

- webplugin/template/mck-sidebox.html
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/687
> fix for waitingqueue bug [master]

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- use the secure route for feedback API
> use secure route for feedback API

- webplugin/js/app/mck-sidebox-1.0.js
- prevent images from being encrypted
- upload and image 
- it should not be encrypted
-
-
> Remove Image encryption logic

- webplugin/js/app/mck-sidebox-1.0.js
- fix the bug and let the conversation open
- use a html payload to show a table in dialogflow bot
`{
"message": "<table id='chatbot-fare-details'><tbody><tr><td>Package fare</td><td>₹2999</td></tr><tr><td>Refundable deposit</td><td>₹500</td></tr><tr><td>Cancellation fee</td><td>₹0.0</td></tr><tr><td>Refundable Amount</td><td>₹3299.0</td></tr></tbody></table>",
"messageType": "html"
}`
-
-
> Fix the issue where the richMessage was not processed. [PROD][URGENT]

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/695
> Remove Image encryption logic [RELEASE-9.3.1]

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/693
> Fix the issue where the richMessage was not processed. [PROD][URGENT][RELEASE-9.3.1]

- webplugin/js/app/mck-sidebox-1.0.js
- Remove Collect email ID banner when conversation is assigned to bot.
- mock: https://kommunicate.atlassian.net/jira/software/projects/FW/boards/15?selectedIssue=FW-2164
https://user-images.githubusercontent.com/22856546/122555387-da695380-d057-11eb-878b-ffd0a0f61ef4.mov
https://user-images.githubusercontent.com/22856546/122555623-27e5c080-d058-11eb-81e1-bce9a7733aeb.mov
-
- 
> FW-2164 Collect email ID from user is coming even though conversation is assign to bot

- webplugin/js/app/kommunicate.js
> Fix error in updateConversationMetadata function 

- webplugin/js/app/mck-sidebox-1.0.js
- Fix restart conversation bot to bot handoff.
- Check for bot-to-bot handoff.
-
-
> Fix restart conversation bot to bot handoff [Chat widget]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
- Removed duplicate text messages in attachment videos 
- attach any more than 2  videos
- then add some text messages within it 
- its show only one-time text message and 2 attachment videos 
-
-
> Fw 2353 [Important] If both msg and image is sent from dashboard, text is not coming in widget

- webplugin/js/app/mck-sidebox-1.0.js
- Load chat widget in IE
-
-
-
> Fix for IE [chat widget]

- webplugin/css/app/km-sidebox.css
- webplugin/css/app/mck-sidebox-1.0.css
- Firefox scrollbar UI bugs
- Install Kommunicate script and check for a scrollbar in Firefox.
---
---
-
-
> FW-2426 Firefox UI bugs [Chat widget]

- webplugin/js/app/mck-sidebox-1.0.js
> Fix chat widget is not loading in IE [development]

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
> Fix card carousel UI [release-9.5]

- webplugin/js/app/mck-sidebox-1.0.js
- Fix dropdown issue for restart conversation.
---
https://user-images.githubusercontent.com/22856546/124594939-02411f80-de7e-11eb-83ee-c1aae60f7afe.mov
-
-
> Fix dropdown issue for restart conversation [Chat widget]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- Add quick replies/intents option in the chat widget.
```
(function (d, m) {
var kommunicateSettings = {
appId: "8ced8a81108c654234a393115cc2ea4f",
popupWidget: true,
quickReplies:["Hi","What's up","Hello"]
};
var s = document.createElement("script");
s.type = "text/javascript";
s.async = true;
var h = document.getElementsByTagName("head")[0];
h.appendChild(s);
window.kommunicate = m;
m._globals = kommunicateSettings;
})(document, window.kommunicate || {});
```
----
https://user-images.githubusercontent.com/22856546/123966277-e4ce0a80-d9d2-11eb-8c54-8256ea1a1a04.mov
-
-
> FW-2362 Add option to trigger intents from a button

- webplugin/css/app/km-sidebox.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-ui.js
- Fix message window UI for IE
(#707)
- check for the message window and FAQ section in IE.
---
---
-
- CSS properties which are not working in IE.
> Fix message window UI for IE [Chat widget]

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
> Fix restart button for resolved conversation [Chat widget]

- webplugin/css/app/mck-sidebox-1.0.css
> Fix support for long string and bot icon color [chat widget]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
- Fix for change default assignee bot from dashboard and close icon aligment for CSAT banner.
---
https://user-images.githubusercontent.com/22856546/125241183-c2a88680-e308-11eb-9964-7bd33aa0a302.mov
---
-
-
> Fix for change default assignee bot from dashboard [chat widget]

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
Reverts Kommunicate-io/Kommunicate-Web-SDK#719
> Revert "FW-2482 Kompose bot stuck in the middle if the conversation is too long [Chat widget]"

- webplugin/js/app/media/media-service.js
-
- Check for TTS in multiple response in chat widget.
-
-
> Fix TTS for multiple response [Release 9.5]

- webplugin/js/app/media/media-service.js
> Fix TTS for chrome [Release-9.5]

- webplugin/js/app/media/media-service.js
- For multiple responses we will pick the latest response for TTS in Chrome.
- For multiple responses we will pick the latest response for TTS in Chrome.
-
-
> fix TTS for Chrome [Chat widget]

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- Ask for CSAT from bot reply.
---
https://user-images.githubusercontent.com/22856546/126479139-41dcc31c-5f35-49d0-ba7e-4980d41bcbe5.mov
```
{
"message": "Hope we answered all your queries. Please reach out to us in case of any more queries.",
"metadata": {
"actionRequest": "askCSAT"
}
}
```
-
-
> FW-2292 Ask for CSAT from bot reply [Chat-widget]

- webplugin/js/app/mck-sidebox-1.0.js
> Fix hide restart conversation button

- webplugin/js/app/kommunicate-ui.js
> Fix-Added close button for feedback banner [Chat widget]

- webplugin/js/app/km-post-initialization.js
- webplugin/knowledgebase/kb.js
- Add a setting so that user can define category to show on which page
- append getFaqByCategory to kommunicate settings with the name of faq category 
-
-
> FW-2535 Show different faqs in different pages based on categories [Important] 

- webplugin/css/app/km-rich-message.css
- all buttons to have 14px font size
-
-
-
> Buttons should have 14px font size [release-9.6]

- webplugin/css/app/km-rich-message.css
- all buttons to have 14px size
-
-
-
> Buttons should have 14px font size

- webplugin/css/app/km-login-model.css
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/744
> FW-2475 Fix

- webplugin/js/app/media/media-service.js
- Execute TTS in Opera Browser, Chrome and Edge.
- Check TTS for multiple responses and long text in Opera Browser, Chrome and Edge.
-
-
> FW-2531 Text To Speech not working in Opera Browser, Chrome and Edge.

- webplugin/js/app/mck-sidebox-1.0.js
- Add assignee image on conversation list window in real time.
---
https://user-images.githubusercontent.com/22856546/128996824-104503d3-8d0f-4af8-b1b6-a4eca0c5e357.mov
-
- Image url is not updating on the `MCK_GROUP_MAP` array when conversation assignee got changed.
> FW-2627 Chat widget bug where agent images doesn't get updated real time

- webplugin/js/app/mck-sidebox-1.0.js
- Enable image encryption 
- Send an image file 
- the image should be encrypted
-
-
> FW-2626 Enable restricted access of attachments

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-app.js
- User can provide `widgetPlatformUrl` parameter instead of `appId`
- The API will return same result and everything after that will proceed same as before
- KM-Server PR: https://github.com/Kommunicate-io/Kommunicate-Server/pull/311
- 
https://user-images.githubusercontent.com/9497860/128695013-3176423d-8279-4bf8-9b4e-eacc2a0bb317.mov
-
-
> Load Chat Widget from Shopify Url

- webplugin/plugin.js
- Add prefix to CSS property.
- Check for chat widget open animation in full screen and normal size.
- https://docs.kommunicate.io/docs/web-customization#full-screen-chat-widget
-
-
> FW-2628 Chat widget animation property conflict with user's website UI

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/knowledgebase/kb.js
- webplugin/template/mck-sidebox.html
- Add a section in FAQ where the user will see categories as shown in helpcenter
- Go to faq
- various categories should appear
https://user-images.githubusercontent.com/19753380/129435495-3e8f672d-de60-49e3-b93d-677f8a7cb78e.mov
-
-
> FW-2294 Show categories in FAQ within chat widget

- webplugin/js/app/kommunicate-ui.js
- Update agent image real time after waiting queue is over
- Check agent image is getting updated in header after waitning queue is over. 
-
-
> Fix agent image update in real time after waiting queue is over

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-app.js
> Shopify release

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-post-initialization.js
The widget was not opening in IE
> FW-2294 fix for IE

- webplugin/js/app/mck-sidebox-1.0.js
> FW-2294 back btn was not working in IE

- webplugin/css/app/km-rich-message.css
- Set image position to left align.
- Check image position in for link preview
---
-
-
> Fix link preview thumbnail position.

- webplugin/js/app/mck-sidebox-1.0.js
- Hide link preview for IE.
- Check for link preview is hidden in IE
---
-
-
> Fix fw-2529 Hide link preview for IE [Chat Widget]

- server/config/config-env.js
> Update config-env.js with new s3 bucket

- webplugin/js/app/mck-sidebox-1.0.js
- Fix link preview for FF.
- Check for link preview in IE.
---
- (#762)
-
-
> Fix link preview for FF [Chat widget]

- webplugin/css/app/mck-sidebox-1.0.css
- Align FAQ answer window to left.
- Check for FAQ answer window.
---
-
-
> Fix faq answer screen window [chat widget]

- webplugin/css/app/mck-sidebox-1.0.css
> Fix text overflow in FAQ category cards

- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/labels/default-labels.js
> Fix remove extra text from the link preview [Release-9.7]

- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- fix faq search issues
- search for any string in faq search box
-
-
> FW-2663 FAQ Search not Working as expected.

- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
- Preview link not working with the text.
- Check for the link preview with a simple text message.
----
https://user-images.githubusercontent.com/22856546/133254998-efa19843-3f72-458a-951f-ac7a0d96b98d.mov
-
-
> FW-2746 Preview link not working with the text [Chat widget]

- webplugin/js/app/mck-sidebox-1.0.js
> Fix support with attachment icon [chat widget]

- server/routers/routes.js
- webplugin/css/app/km-login-model.css
- webplugin/css/app/km-rich-message.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
- webplugin/knowledgebase/kb.js
- webplugin/plugin.js
- webplugin/template/mck-sidebox.html
> Merge Release 9.7.1 into master

- webplugin/js/app/kommunicateCommons.js
- webplugin/template/mck-sidebox.html
- Fix video uploading for captured video from mobile device.
-Check for video uploading for `captureVideo: true` property in KommunicateSettings.
-
-
> fix video capture uploading issue

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
> Fix video uploading issue Chat Widget

- webplugin/js/app/kommunicate-ui.js
- Message should not be covered by CSAT rating card.
- Start a conversation and send a long message from the dashboard and check CSAT banner should not cover the last message in the chat widget.
---
https://user-images.githubusercontent.com/22856546/134628707-d5a20f48-3048-4a77-828b-f602ff7f05c6.mov
-
-
> FW-2794 Message should not be covered by CSAT rating card

- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-sidebox-1.0.js
> Fix video capture chat widget [development]

- webplugin/js/app/zendesk-chat-service.js
-
- Check for the chat widget in IE.
-
-
> Fix chat widget loading in IE

- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicateCommons.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Added restriction for CSAT according to plan subscription.
- Check for CSAT according to plan subscription.
```{
"message": "We are resolving this conversation. Please reach out to us in case of any more queries.",
"metadata": {
"actionRequest": "askCSAT"
}
}
```
---
https://user-images.githubusercontent.com/22856546/134193101-818d6e18-038a-42c5-b008-006d9002f51e.mov
-
https://user-images.githubusercontent.com/22856546/134192816-095d0b4f-acf9-4fe0-81a9-a0b90354fdaa.mov
-
-
> FW-2795 Call API for CSAT Rating for Plan Restriction [Chat Widget]

- webplugin/js/app/mck-sidebox-1.0.js
- prevent xss attack
- open a widget instance 
- create a conversation with dialogflow bot
- copy the xss payload and paste it in the input box
- the script should not get executed
-
-
> FW-3068 Fix XSS vulnerability

- webplugin/js/app/km-widget-custom-events.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- fixed an issue where the faq section UI was breaking in a particular scenario
- open widget
- go to faq, select a category, select and article and click on close widget button
- now again open the widget and faq section. The ui should be proper
-
-
> Bug fix for release 10.0

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
- fix the ui where the single card was on in line with other messages
-
-
-
> UI bug fix for single card

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-widget-custom-events.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/801
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/802
> Bugfixes from rel 10.0 

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/803
> FW-3136[ BUGFIX] fixed bug where the image was not opening

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-ringtone-service.js
- The greeting notification sound was not working as aspected.
- open a webpage, clear the session storage
- add the script 
- the greeting message should appear and the notification sound should trigger as per the setting
-
-
> FW-3140 Greeting Message Sound in iOS safari mobile

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-sidebox-1.0.js
- Update the user availability status in realtime
- init a chat with agent
- change the availability status of agent from dashboard
- the change should be visible in the widget in realtime
-
-
> FW-3096 The Online Mark is not displayed sometimes in the chat widget. Online offline Status not updated in the real time

- webplugin/js/app/kommunicate-ui.js
added skipEncryption to getUrlFromBlobkey
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/805
- fix a bug where the image was not opening in encrypted accounts
-
-
-
> FW-3136 Added encryption support to encrypted accounts

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-ringtone-service.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/806
> FW-3140 Greeting Message Sound in iOS safari mobile [RELEASE-10.0.1]

- webplugin/css/app/km-rich-message.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-ringtone-service.js
- webplugin/js/app/mck-sidebox-1.0.js
> Merging Release 10.0.1 to Master

- webplugin/js/app/km-message-markup-1.0.js
> Bugfixes for release 10.1

- webplugin/js/app/km-message-markup-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/813
> Bugfixes for rel 10.1

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- Fixed multiple bugs  
- reproduction steps mentioned in the jira ticket
-
-
> FW-3097 Bot name displayed outside the chat conversation. FAQ displayed instaed of agent or bot name. [18th JAN]

- webplugin/js/app/mck-sidebox-1.0.js
- added a check to prevent undefined from getting passed to JSON.parse().
- Please test the code with an website env where
1. the session storage is not available initially.
2. kommunicate is not present in local storage.
-
-
> FW-3229 The widget is initialising with empty header

- .gitignore
- webplugin/js/app/zendesk-chat-service.js
Refer https://github.com/Kommunicate-io/Kommunicate-Server/pull/388
> [TD-2356]Add support for File sending events in Zendesk

- rich-messages-code-sample/amazon-lex-lambda/form-using-custom-payload.js
- rich-messages-code-sample/readme.md
- add sample for lex lambda form custom payload
> add sample for lex lambda form custom payload

- rich-messages-code-sample/kompose-webhook/app.js
- rich-messages-code-sample/kompose-webhook/package.json
- rich-messages-code-sample/kompose-webhook/readme.md
> add Kompose webhook sample

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
- create new conversation if current one is assigned to agent in case of fresh load
- verified in local
> create new conversation if current one is assigned to agent in case of fresh load

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/lib/js/recorder.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/825
> [BUGFIX] FW-3192 Add voice note feature to chat widget

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/835
> Fixed a bug where the submit btn was breaking on form submit

- webplugin/css/app/km-voice-note.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/css/app/mck-sidebox-1.0.min.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-dom-event-listener.js
- webplugin/js/app/media/media-service.js
- webplugin/js/app/media/typing-area-dom-service.js
- webplugin/lib/js/Fr.voice.js
- webplugin/lib/js/recorder.js
- webplugin/pluginOptimizer.js
- webplugin/template/mck-sidebox.html
- the feature was reverted in last release as it was not ready. Now reintroduced it.
-
-
-
> The Voice note feature was not working

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/lib/js/recorder.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/827/commits
> updated voice note service worker

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/zendesk-chat-service.js
- Pass chat transcript as attachment or text once the chat is handed over to human agent in Zendesk.
- Tested locally
- Demo of chat transcripts
-
-
> [TD-2463]Added Transcipt sending logic while passing the chat to Zendesk Agent

- webplugin/js/app/mck-sidebox-1.0.js
- remove the bug where the encrypted audio was not playing in specific condition
- open the chat widget
- create a new conversation
- send an audio as first message
- the audio was not playable previously
-
- The decryption logic was present inside the scroll eventListner. This eventListner was not triggering when the messages were less 
> FW-3468 MP3 files and audio not playable inside chat widget after sending.

- webplugin/js/app/mck-sidebox-1.0.js
> bugfix for Change default upload platform [DEVELOPMENT]

- webplugin/js/app/mck-sidebox-1.0.js
- the images should get displayed on scroll event also because the links expire after 15 mins
- fix the bug in IE as for..of loop is not supported in IE
-
-
-
> FW-3468 [BUGFIX] 

- webplugin/js/app/zendesk-chat-service.js
- use *.kommunicate.io for attachments in zendesk transcripts
- In below image notice attachment url
> [TD-2507] use *.kommunicate.io for attachments in zendesk transcripts

- webplugin/css/app/km-rich-message.css
- webplugin/css/app/km-voice-note.css
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/css/app/mck-sidebox-1.0.min.css
- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-dom-event-listener.js
- webplugin/js/app/media/media-service.js
- webplugin/js/app/media/typing-area-dom-service.js
- webplugin/js/app/zendesk-chat-service.js
- webplugin/lib/js/Fr.voice.js
- webplugin/lib/js/recorder.js
- webplugin/pluginOptimizer.js
- webplugin/template/mck-sidebox.html
> Merge Release 10.3.1 into master

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
User Providing a vaild email address should be allowed to login to the Widget.
Checked by trying to login to the widget with some Invalid email address.
Got to know the code flow of Kommunicate-Web-SDK repo
NA
> [FF-92] PreChat login email validation.

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
Reverts Kommunicate-io/Kommunicate-Web-SDK#854
The Changes were Merged to Master instead of development and also there was a Bug so Reverting this.
> Revert "[FF-92] PreChat login email validation."

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
User Providing a vaild email address should be allowed to login to the Widget.
Checked by trying to login to the widget with some Invalid email address.
Got to know the code flow of Kommunicate-Web-SDK repo
NA
> Ff92 cherry pick

- webplugin/js/app/zendesk-chat-service.js
- Fix Zopim Chat transcript bug where sometimes Agent's name was coming instead of Bot's name.
- Tested locally. Changes are working as expected.
> [TD-2538] Fixed Zopim Chat transcript bug

- webplugin/css/app/km-rich-message.css
- Adjusting padding for the quick reply button same as other buttons
- local chrome
-
-
> Adjusting padding for quick reply button

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
- webplugin/template/mck-sidebox.html
- Resolve conversation on Chat-widget and Dashboard once the ticket/chat gets closed on Zendesk.
- Tested locally. All functionality is working fine.
- How we resolve conversation on chat-widget side.
> [TD-2623] Resolve conversation on Chat-widget and Dashboard once the ticket/chat gets closed on Zendesk.

- webplugin/js/app/mck-app.js
- add support for csp enabled websites
- enable csp in a html webpage and add widget script.
- initially the widget will not open
- add "km-widget-script" as id to km script tag and add nonce attribute to it
- now the widget should function normally
-
-
> FW-3740 Add an option to pass nonce value for CSP

- webplugin/template/mck-sidebox.html
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/863
> Change powered by [development]

- webplugin/template/mck-sidebox.html
- Update powered by to Kommunicate and add AI chatbot keywords
-
-
-
> Change powered by

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
- webplugin/template/mck-sidebox.html
This reverts commit cac841096465e85745690ac2cc57df3b5178965a, reversing
changes made to db64f2477b82eebdd06ea25858f34f2db1016bf6.
-
-
-
-
> Revert "Merge pull request #864 from Kommunicate-io/TD-2623"

- webplugin/js/app/km-rich-text-event-handler.js
-
-ran it locally and tried sending a form
-
-bug fix: before forms didnt consider application/json as a requestType
> [TD-2601] Partner Page Set request handler in Web-SDK

- webplugin/template/mck-sidebox.html
- powered by updated to "Kommunicate Conversational AI Chatbot"
-
-
-
> Change Powered by in v1 chat widget

- webplugin/js/app/mck-sidebox-1.0.js
- the media will be directly upload upon paste event
**This is first of many changes to come. Discussed with Rajeesh and he told to file this separately**
- copy an image and paste it in the input box
-
-
> FW-3606 Copy & paste of the images on the  chat widget

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
- Fixed Zendesk End Chat Resolution bug
- Tested locally.
> Fixed Zendesk End Chat Resolution bug

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/877
> Merge FW-3606 in release 10.7

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/877
> Merge FW-3606 in  development

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
-Pass Pre chat lead collection data to Zendesk
-Ran the code locally to check if data is being passed to Zendesk
-
-
> [TD-2705] Pre chat lead collection

- webplugin/js/app/zendesk-chat-service.js
> Please refer: https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/892
> [TD-2743] Remove zendesk's tokens dependency in zendesk chat integration [RELEASE]

- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- The FAQ button's text can be changed by labels
- set the 'faq' label to any other text
-
-
> FW-4000 Make FAQ button text a label

- webplugin/js/app/km-widget-custom-events.js
- webplugin/js/app/mck-sidebox-1.0.js
> Patch: Support Zendesk with custom-events

- webplugin/js/app/km-rich-text-event-handler.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/869
> [TD-2601] Partner Page Set request handler in Web-SDK [DEVELOPMENT]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-post-initialization.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/888
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/899
> Resolve merge conflicts from Release branch

- webplugin/plugin.js
- webplugin/template/mck-sidebox.html
- Removing Unnecessary anchor so that they will not show as a backlink on customers' website
- Local Env
> Removing Unnecessary anchor

- webplugin/js/app/mck-sidebox-1.0.js
- The onMessageReceived events were triggering multiple times
- test for zendesk and normal use case seperately.
-
-
> Fix for events being triggered multiple times.

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/906
> Fixed a bug where events were not passed to event map

- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/906
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/907
> Fix for events being triggered multiple times [RELEASE-10.8.1]

- webplugin/js/app/km-utils.js
-add secure flag cookies
-tested on locally
-
-
> secure flag cookies

- server/config/config-env.js
> remove temp change

- webplugin/js/app/zendesk-chat-service.js
-Phone number details should be passed to zendesk zopim.
-check if entered phone number is similar to the phone contact in zopim user.
-
-
> [TD-2768]Add phone number in zopim(1)

- webplugin/pluginOptimizer.js
- webplugin/template/serve.json
- location picker should not break
- emoticons should not break.
-
-
-
> Location picker was not working [BUG-FIX]

- webplugin/pluginOptimizer.js
- webplugin/template/serve.json
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/922
> Location picker was not working [BUG-FIX][RELEASE]

- webplugin/js/app/mck-sidebox-1.0.js
> Removed arrow functions [BUGFIX] [RELEASE]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/plugin.js
- Add a new form of popup message
- add this code in the widget script under kommunicateSettings
```appSettings: {
chatPopupMessage: [
{
message: [
"TaxBuddy saves 2k+ hours every month using Kommunicate’s chatbot",
"Kommunicate resolves 60% of incoming customer service requests for Epic Sports",
"California State University uses Kommunicate to handle queries from over 20k students",
],
templateKey: 3,
buttons: [
{
label: "Support",
// onClickAction: function (){
//     console.log('clickFunctionOne');
// },
},
{
label: "Get Demo",
onClickAction: function () {
console.log("clickFunctiontwo");
},
},
],
},
],
},
```
-
-
> FW-3962 Implement trust factor for KM website chat widget

- webplugin/js/app/kommunicate-ui.js
fix a bug where the widget was not opening in full
> [BUGFIX] FW-3962

- webplugin/js/app/mck-sidebox-1.0.js
> Bugfixes from release 10.9

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
wanted to provide settings to turn chat widget time in 24 hours
please used "timeformat24hours":true in kommunicateSettings to enable this
-
- [. ] I have tested it locally and all functionalities are working fine.
- [ .] I have compared it with mocks and all design elements are the same.
- tested on local browser 
checked for new conversations and old conversations
-
-
> addedFeatureFor24HoursFormat

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- instead of media compression we are providing a way which can be used to upload the videos of size > 25 mb.
- need to add this in kommunicate settings
- attachmentHandler: function(file){}
- the function will be a custom function
- you will need a setup for testing Please connect with me for that.
-
-
> FW-4015 Media compression 25MB is the limit when being uploaded.

- webplugin/js/app/mck-sidebox-1.0.js
- Bug fix title change
- Bug fix title change
> Bug fix title change

- webplugin/js/app/mck-sidebox-1.0.js
> Bug fix title change [Release 10.9.2]

- webplugin/css/app/mck-sidebox-1.0.css
- FAQ card style is Fixed. When the FAQ card has a maximum letter length(150 characters), then the last line is chopped from the middle, and only half part of the letters is visible to users.
- I've tested the code locally.
-
-
> FAQ is chopped from the Bottom

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
- date and radio validation
-
-
-
> date and radio validation

- webplugin/js/app/mck-sidebox-1.0.js
- SPA Title change fix
- by running web SDK in local and checking in customer website.
- Title change not working for SPA
-
> SPA Title change fix [Development Branch]

- webplugin/js/app/mck-sidebox-1.0.js
> SPA Title change fix [Patch 11.0.1]

- webplugin/js/app/km-message-markup-1.0.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- fix the bug where a newly uploaded file was inaccessible
- test all types of file uploads
-
- the url was initially wrong and was getting updated to encrypted url
> FW-3657 Send a PDF in the Chat widget Now click on the PDF the Page breaks.

- webplugin/js/app/km-richtext-markup-1.0.js
- Make the form's radio & checkbox button clickable.
- Have tested code locally
-
-
> make form label clickable

- webplugin/css/app/mck-sidebox-1.0.css
> FW-4293 - Trust factor bug

- webplugin/js/app/mck-sidebox-1.0.js
- Fix the Synaxerror when user use pre lead collection.
- 
-
-
https://user-images.githubusercontent.com/94929705/191758866-d50baf6d-e2d8-46a7-9f7b-a3ed3c03e07d.mov
> Fix the Syntaxerror when user use pre lead collection.

- webplugin/css/app/km-rich-message.css
- Button text overflow [Fix](https://kommunicate.atlassian.net/browse/FW-3813) 
- Local chrome
- Before
- After
> Button OverFlow Fix 

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/plugin.js
> updated css to restrict view

- webplugin/js/app/kommunicate-ui.js
> fixed issue where csat was triggering even if askCSAT was false

- webplugin/js/app/mck-sidebox-1.0.js
> Updating api key - [Release 11.0.2]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/plugin.js
> Trustfactor improvement - updated css to restrict view

- webplugin/js/app/mck-sidebox-1.0.js
- updating api key
- Running widget on local and sending locations from dashboard
-
- Mismatch of API key
> Updating api key

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
> merge Release 11.0.2 into master

- webplugin/css/app/mck-sidebox-1.0.css
- if we send img and location then tick icon not showing properly
-
-
-
> Bug fix tick icon not showing properly msg

- webplugin/css/app/mck-sidebox-1.0.css
> Bug fix where tick icon not showing properly.

- webplugin/js/app/km-richtext-markup-1.0.js
> fixed the bug for IE

- webplugin/js/app/events/applozic-event-handler.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
- Bug fix when speech is going on and the user clicks to turn off button then the speech will not turn off.
-
-
-
> Speech bug fix.

- webplugin/js/app/events/applozic-event-handler.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
> Speech bug fix

- webplugin/js/app/mck-sidebox-1.0.js
> Initialised OnInIt function while preChatLead is on [Release - 11.1.1]

- webplugin/js/app/mck-sidebox-1.0.js
- Initialised OninIt function while preChatLead is on
- by enabling pre-chat lead collection and updating CSS by the onInit function from the chat widget
- function not called
> Initialised OnInIt function while preChatLead is on

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- The bot icon disappears after the button is clicked - hidePostCta Enable
- Locally
-
> The bot icon disappear after the button is clicked [Prod Bug]

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
> logout after agent leaves

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
Patch for Zopim multi threading bug
> patch for zopim multi threading bug

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
> [TD-2651] Double agent message

- webplugin/css/app/km-rich-message.css
- Centring Card carousel options
- enabling chat widget on local
- https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/945
> Centring Card carousel options

- webplugin/css/app/km-rich-message.css
> Centring Card carousel options [Release - 11.1.3]

- amplify.yml
- package.json
Add properties for europe region
-
-
-
-
> Add properties for europe region

- playwright_test/README.md
> added readme file

- SECURITY.md
- Kommunicate Security Policy and Procedures
- How to report the issue
- Disclosure Policy
> Add Security.md file on Chat widget [For Security Issues] [FW-4654]

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
release branch for https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/991
> FW-4562 Fix zendesk chat logic [chat-widget][RELEASE]

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/zendesk-chat-service.js
- Fixed the issue where authenticated users and agent were getting multiple messages 
- Fixed the issue where sessionTimeout was not getting picked from kommunicateSettings
1st
- integrate zendesk 
- enable prechat lead 
- start conversation and check for multiple messages.
2nd
- check for session timeout.
-
-
> FW-4562 Fix zendesk chat logic [chat-widget]

- webplugin/js/app/mck-sidebox-1.0.js
Please refer to this PR https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/997
> Fix the bug where the widget stuck in loading state on click of back button

- .github/danger.yml
- .github/pull_request_template.md
- .github/workflows/danger.yml
- dangerfile.js
- package.json
- Automate Common checks in PR
-
- danger.js
> Automate Common checks in PR [Development] [FWH-40]

- dangerfile.js
- webplugin/js/app/km-widget-custom-events.js
- adding ga4 support
- 1 > by adding ga4 id by using postman to the db
- 2 > by downloading and checking google analytics debugger
- 3 > by using ga4 [debug](https://analytics.google.com/analytics/web/#/a109137709p323753273/admin/debugview/overview?params=_r..layout.pageNumber%3D0%26_u..pageSize%3D25) window
https://ga4-event-test.di4txnja072ge.amplifyapp.com/ga4Test.html
> Google Analytics Integration to Google Analytics 4 [TDH-35]

- webplugin/template/chat.html
- Add query parameters for iframe
- Pre Chat Lead on from dashboard - Chat widget opens with Pre Chat Lead Form
If Disabled - Conversation starts
-
-
> Add query parameters for iframe [FFH-49]

- webplugin/css/app/mck-sidebox-1.0.css
- User comment should not overflow from the widget.
-
-
-
> User comment should not overflow from the widget.

- webplugin/template/chat.html
- Add support for query parameter for bot ids in iframe
-
-
-
> Add support for query parameter for bot ids in iframe

- webplugin/js/app/km-widget-custom-events.js
- if there is no ga4 integration on dashboard, chat widget is not loading
-
-
-
> Google Analytics-4 Bug fix

- webplugin/js/app/zendesk-chat-service.js
- The website url should be updated in a zendesk chat
- Login into zendesk 
- setup departments in the zendesk
- setup triggers to route tickets to specific department when coming from a specific url
- integrate that account in your application
- create a conversation in widget from the configured page
The conversation should be routed to configured URL
-
-
> FWH-122 Add support for updating user url in zopim [chat-widget]

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- when we send audio from mobile it should be handled in web sdk
- I have tested it from https://test.prochnost.tk/widget-test
-
-
> Fwh-67 dev Audio Message contentType: 8 handling | Web SDK

- webplugin/js/app/media/media-service.js
- Adding Voice-to-text support on basis of browser lang 
- changing browser lang chrome://settings/languages
- Voice input from chat widget
> Adding Voice-to-text support on browser lang 

- webplugin/template/chat.html
- Fix  to make chat widget full screen  when using through Iframe- currently, after 700px or larger it was breaking
- Without pre chat lead -
width give 100%
with pre chat lead enabled
test for height and width 100%
-
-
> Iframe Width Issue [FFH-115]

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
> TDH-94 added new lead collection rich message  [Development]

- webplugin/plugin.js
- Implemented prevention of click-jacking in chat widget
-
-
-
- 
> FWH-66 Missing Anti-clickjacking Header is missing in Chat Widget

- webplugin/js/app/kommunicate.js
- add array checks for agentIds and botIds when creating groups
- before:
- after:
```js
var defaultSettings = {
"defaultBotIds": "3-hsi6p",
"skipRouting": true,
};    
Kommunicate.updateSettings(defaultSettings); 
```
```js
(function(d, m){
var kommunicateSettings = 
{"appId":"6a5aa6545f2ad310d986c80bbc290b9e","popupWidget":true,"automaticChatOpenOnNavigation":true, "defaultBotIds": "3-hsi6p",
"skipRouting": true,};
var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
var h = document.getElementsByTagName("head")[0]; h.appendChild(s);
window.kommunicate = m; m._globals = kommunicateSettings;
})(document, window.kommunicate || {});
```
> [FWH-276] add array checks for agentIds and botIds when creating groups

- webplugin/js/app/mck-sidebox-1.0.js
- Google login and maps - move to new GCP Project
-
-
-
- 
> FWH-319 Google login and maps - move to new GCP Project

- webplugin/css/app/km-rich-message.css
- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/js/app/mck-app.js
- Add support to show checkboxes as buttons
- pass checkboxAsMultipleButton as true in kommunicateSettings
-
-
> FWH-328 Multiple Select Buttons

- webplugin/js/app/km-richtext-markup-1.0.js
- ${msgKey} will not work for IE
-
-
-
- 
> getFormTemplate code improvement

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Added support to show a static message at top of the conversation section
- add "staticTopMessage": "Messages in this chat are end-to-end encrypted. No one outside this chat can read or listen to them." in kommunicateSettings
-
-
> FWH-345 Encryption Messages 

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
> TTS for IOS mobile browser is not working [TDH-255] [Release - 11.3.6]

- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
- Code Improvements TTS
- Fix IOS devices TTS not working
- Checked on Mac (safari, chrome, firefox, edge)
- Checked on Windows (chrome, firefox, edge)
- Checked on Android Web (chrome, firefox, edge)
- Checked on IOS Web (Safari)
- IOS devices did not run speech API automatically, so manually triggering the fake empty voice for IOS
> TTS for IOS mobile browser is not working [TDH-255]

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
> FWH- 301 On btn click chat widget not working as expected if user's pre chat is enabled.

- webplugin/js/app/media/media-service.js
> STT Support IOS [TDH-255] [Release-11.3.6]

- webplugin/plugin.js
Reverts Kommunicate-io/Kommunicate-Web-SDK#1040
> Revert "FWH-66 Missing Anti-clickjacking Header is missing in Chat Widget"

- webplugin/js/app/media/media-service.js
- fixed release branch issues
-
-
-
- 
> Fixed release branch issues [Release-11.4]

- webplugin/js/app/km-richtext-markup-1.0.js
- the template id 7 was getting hidden if there were no buttons
-
-
-
- 
https://kommunicate.atlassian.net/browse/FWH-457
> FWH-457 Hide post CTA bug fix for List template 

- webplugin/css/app/km-rich-message.css
-
the issue was that the image preview in the link was not clearly visible for the logo
it should be clear like this, so fixed it 
- 
> Updated css for link preview image

- webplugin/js/app/kommunicate.js
> Commenting Code [TDH-301]

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1077
> FWH-525 Add support for showing custom message if file limit is exceeded [RELEASE-11.4.3]

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1078
> FWH-529 Session is not getting stored properly [RELEASE-11.4.3]

- webplugin/js/app/km-utils.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- the bot config was not working as per expectations
- Test general flow of converstion
- test the sessionTimeout configuration
- test the different bots on diff pages
- test KM_CHAT_CONTEXT config
-
-
- 
> FWH-529 Session is not getting stored properly

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
> Time stamp and bot icon are not visible while hidePostCta is enabled [RELEASE-11.4.4]

- webplugin/lib/css/intl-tel-lib.css
- Spacing issue in the Pre-chat lead form 
-
-
-
> FWH-556 Spacing issue in the Pre-chat lead form 

- webplugin/js/app/mck-sidebox-1.0.js
- Add support for team id filter in analytics related APIs 
- start a conversation
- genrate feedback
- check in dashboard csat analytics section (select relevant team from the dropdown)
- repeat the steps for various teams
-
-
- 
> FWH-387 Add support for team id filter in analytics related APIs

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- Add bot testing within dashboard - Part 2
-
-
-
- 
> FWH-486 -: Add the one function for restart the current conversation

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
> TDH-338 Pseudonym appearing in place of Name in first chats sometimes [dev]

- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
> TDH-338 Pseudonym appearing in place of Name in first chats sometimes [release]

- webplugin/js/app/km-widget-custom-events.js
- Sending events to Google Analytics4 as per gtag
- By adding ga4 script on local website then intialize the script on that website(the same ga4 id i added on dashboard)
- ga4 new event firing [instructions](https://developers.google.com/analytics/devguides/collection/ga4/events?client_type=gtag)
- 
> Sending events to Google Analytics4 as per gtag [TDH-331]

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/plugin.js
- In Notification popup banner close btn is not visible fixed that.
- https://intentive-ai.slack.com/archives/C0178DHF2RH/p1692300496047539
-
-
-
- 
> In Notification popup banner close btn is not visible fixed that.

- webplugin/js/app/km-widget-custom-events.js
> Sending events to Google Analytics4 as per gtag [Release-12.02] 

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/css/app/style/style.css
- webplugin/scss/components/_km-login-modal.scss
- release 12.0.2 bug fixes
-
-
-
- Before
- After
> release 12.0.2 bug fixes

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/css/app/style/style.css
- webplugin/js/app/km-message-markup-1.0.js
- webplugin/plugin.js
- webplugin/scss/components/_km-chat-popup.scss
- Fix the left side widget pop up style issue
-
-
-
- 
> Fix the left side widget pop up style issue

- webplugin/css/app/style/style.css
- webplugin/plugin.js
- webplugin/scss/components/_km-chat-popup.scss
> fix the top pop style

- webplugin/js/app/mck-app.js
> Change the map default api key

- webplugin/js/app/mck-app.js
> Map is not loading

- webplugin/knowledgebase/kb.js
-  No articles to show is coming in widget msg area
- 
-
-
- 
> FWH-903 -: No articles to show is coming in widget msg area

- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-sidebox-1.0.js
- Add Setting for Disable Text Area
- tested when the chat is assigned to bot
- tested when chat is assigned to human
-
-
- 
> FFH-416 Add Setting for Disable Text Area

- webplugin/css/app/mck-sidebox-1.0.css
- To show the placeholder text when user clicks on text area but haven't write anything yet
-
-
-
- 
> Ffh 291-development To show placeholder when the cursor is inside the Message Box in Chat Widget 

- webplugin/js/app/km-richtext-markup-1.0.js
> If form have all elements type is hidden then UI is breaking in chat widget

- .gitignore
- webplugin/js/app/km-richtext-markup-1.0.js
> FWH-951 -:  If form have all elements type is hidden then UI is breaking in chat widget [dev]

- .gitignore
- webplugin/js/app/km-richtext-markup-1.0.js
-  If form have all elements type is hidden then UI is breaking in chat widget 
-
-
-
- 
> FWH-951 -: If form have all elements type is hidden then UI is breaking in chat widget

- webplugin/js/app/kommunicate.js
- Add the empty string if agentId is not given in params
-
-
-
- 
> Add the empty string if agentId is not given in params

- webplugin/js/app/media/media-service.js
> Adding Long text char support in TTS - [TDH-517] [Release-12.2.1]

- webplugin/js/app/media/media-service.js
- adding Long text char support in TTS
- locally chrome by adding long text in bot response and listen the complete message
- Deploy this branch to widget-test and check
> Adding Long text char support in TTS - [TDH-517]

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
> Add the empty string if agentId is not present

- webplugin/css/app/km-sidebox.css
- webplugin/js/app/mck-app.js
- webplugin/template/mck-sidebox.html
-  Add the churn banner 
Original Pr - https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1124
-
-
-
- 
> Ffh 242 release 12.2.2

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/scss/components/_km-hidePostCta.scss
- webplugin/scss/style.scss
- Fix hidePostCTA related bug
-
-
-
- 
> FWH-945 -: Fix hidePostCTA related bug 

- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/scss/components/_km-hidePostCta.scss
- webplugin/scss/style.scss
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1141
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1140
> Hide post cta 12.2.3

- webplugin/js/app/kommunicate.js
- Fix the hidePostCTA is not working for list
-
-
-
- 
> FWH-981 -: Fix the hidePostCTA is not working for list

- webplugin/js/app/mck-sidebox-1.0.js
- change the text when "text to speech" icon is off for primaryCTA
-
-
-
- 
> FWH-959 -: change the text when "text to speech" icon is off for primaryCTA

- webplugin/js/app/km-richtext-markup-1.0.js
- webplugin/scss/components/_km-form-template.scss
- Automatically selected form Prefil
```
{
"message": "Submit your details",
"metadata": {
"payload": [
{
"type": "radio",
"data": {
"title": "What do you identify as:",
"name": "Gender",
"options": [
{
"label": "Male",
"value": "male",
"selected": true
},
{
"label": "Female",
"value": "female"
},
{
"label": "Other",
"value": "other"
}
]
}
},
{
"data": {
"title": "Choose your Symptoms",
"name": "Associated Symptoms",
"options": [
{
"value": "Headache",
"label": "Headache",
"selected": true
},
{
"value": "Cough",
"label": "Cough"
},
{
"value": "Breathlessness",
"label": "Breathlessness"
}
]
},
"type": "checkbox"
},
{
"data": {
"name": "Submit",
"action": {
"postFormDataAsMessage": "true",
"postBackToKommunicate": "false",
"requestType": "json",
"formAction": ""
},
"type": "submit"
}, …
```
> FWH-1105 -: Automatically selected form Prefil

- webplugin/template/chat.html
- add support for teamId in iframe mode
- created a script to launch the iframe widget
- `<iframe
style="border: none;"
height="600px"
width="400px"
src="http://localhost:3030/chat?appId=2f84858de17433911bfb65b3740a55908&teamId=685828&agentIds=anuj%2Bop260623@kommunicate.io,pooja.poojagc@gmail.com&assignee=anuj%2Bop260623%40kommunicate.io"
allow="microphone; geolocation;"
>
</iframe>`
-
-
- 
> Added support for TeamId in iframe

- webplugin/js/app/kommunicate-ui.js
- The link preview is broken in case where the urls are redirecting
-
-
- https://kommunicate.atlassian.net/browse/FWH-1187?focusedCommentId=48480
- 
> The link preview is broken

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/km-richtext-markup-1.0.js
> KM_TRIGGER_EVENT is not working in case of list item - [TDH-656]

- webplugin/js/app/km-nav-bar.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/knowledgebase/kb.js
- webplugin/pluginOptimizer.js
- After human handoff talk to human button should not visible
-
-
-
- 
> FWH-1057 -: After human handoff talk to human button should not visible

- server/README.md
- update the readme file to run the websdk in local
- debug the production websdk in localhost
-
-
-
- 
> update the readme file to run the websdk

- webplugin/js/app/mck-sidebox-1.0.js
- Fixed the svg image is not loading
-
-
-
- 
> Fixed the svg image is not loading

- webplugin/js/app/km-rich-text-event-handler.js
- webplugin/js/app/mck-sidebox-1.0.js
- on clicking on button more than one, intents are triggering every time
-
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/assets/109517510/7e4e2a24-324d-4d6f-8739-bd26cdc3925c
- 
> FWH-1089 -: on clicking on button more than one, intents are triggering every time

- webplugin/js/app/components/typing-service.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- When the bot displays a long message, the user has to scroll up to read. This needs to be avoided.
-
-
-
- 
> FWH-1315 -: When the bot displays a long message, the user has to scroll up to read. This needs to be avoided.

- webplugin/js/app/components/typing-service.js
- Fix the null issue in currentMessage
-
-
-
- 
> Fix the null issue in currentMessage

- webplugin/bundleFiles.js
- webplugin/css/app/mck-sidebox-1.0.css
- webplugin/lib/css/font-import.css
- webplugin/scss/base/_base.scss
- webplugin/template/mck-sidebox.html
- Fixed the accessibility errors.
-
-
-
> TDH-813 -: Fixed the accessibility errors.

- webplugin/js/app/km-rich-text-event-handler.js
- Fix the form issue where the label have space
- Element has class -> `firstname` but in query selector class look like `first name`
-
-
-
- 
> Fix the form issue where label have space

- customHttp.yml
> Prevent the html file to being cache

- webplugin/bundleFiles.js
- webplugin/js/app/conversation/gen-ai-service.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-sidebox-1.0.js
- Bot Generative AI- Phase 1 (Widget)
- tokenize response is supported only in custom bot for now 
- `generativeResponse` parameter should be true in  the bot.
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/assets/109517510/0b7e7a23-e11e-46bc-81d5-2f436e43891c
-
-
- 
> TDH-765 -: Bot Generative AI- Phase 1 (Widget)

- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- added function to get user Location from chat widget
-
-
-
- 
> function to get user Location from chat widget CUS-33

- webplugin/js/app/kommunicate-ui.js
- webplugin/template/chat.html
- fix the iframe scroll issue
- tested locally
- 
> The customer is using Iframe and when the iframe loads the page scrolls down [CUS-36]

- webplugin/js/app/km-richtext-markup-1.0.js
-added image preview for rich message images in a bot response.
-
-
-
- 
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/assets/169023124/916593b6-1628-4d79-817e-dcfaea915eb6
> added image-preview for rich message image CUS-223

- package.json
- webplugin/js/app/mck-sidebox-1.0.js
- Fix the Custom Input Field issue
- Again asking for the email even though user already shared the mail
-
-
- 
> TDH-1067 -: Fix the Custom Input Field issue

- webplugin/js/app/km-richtext-markup-1.0.js
> Release image preview

- webplugin/bundleFiles.js
- webplugin/js/app/events/applozic-event-handler.js
- webplugin/js/app/km-nav-bar.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/js/app/media/media-service.js
- webplugin/js/app/media/typing-area-dom-service.js
- webplugin/js/app/storage/cookie-service.js
- webplugin/js/app/storage/local-service.js
- webplugin/js/app/storage/session-service.js
- webplugin/js/app/storage/storage-service.js
- webplugin/terser.config.js
- Parse only the widget-related cookies
- No need to decode the cookies because we are encoding the cookies
-
-
-
- 
> TDH-1055 -: Parse only the widget related cookies

- webplugin/js/app/kommunicate-client.js
- webplugin/js/app/kommunicate.js
- webplugin/js/app/mck-app.js
- Added support for defaultConversationMetadata
- Locally 
- 
> Added support for defaultConversationMetadata

- amplify.yml
- webplugin/js/app/kommunicate.js
- HidePostCTA not working properly 
- It breaks only if the welcome msg contains two button payload where first payload contains the quick replies buttons and second one contains the submit button
- https://www.kommunicate.io/livechat-demo?appId=2c3b81318c6232a9e94a28f3783a64c63&botIds=richmessagetesting-v07e2&assignee=richmessagetesting-v07e2
-
-
- 
> TDH-951 -: Fix the hidepost cta is not working welcome msg

- webplugin/css/app/km-sidebox.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
> Release business hour widget changes

- webplugin/css/app/km-sidebox.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
- These are widget changes for business hour feature.
- Message which is present in the dashboard should be visible to user when user interacted outside business hour
- Tested locally; by changing default team and checking message;
- 
> Widget changes for Business Hour [FWH-2499]

- webplugin/js/app/mck-sidebox-1.0.js
- when we click on ESC button  "image preview" should be closed.
-
-
-
- 
> added support for esc button on image preview

- webplugin/js/app/mck-sidebox-1.0.js
- Fix summary in contact box issue in widget conversation summary bug
- Tested by generating the summary
- 
#1229
> Summary Text in chat widget

- webplugin/js/app/mck-sidebox-1.0.js
#https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1225
- Do not create user for churned customer
-
-
-
- 
> FWH-2052 Register/initialize api calls should not create user if customer is churned

- webplugin/bundleFiles.js
- webplugin/js/app/components/answer-feedback-service.js
- webplugin/js/app/km-utils.js
- webplugin/js/app/km-widget-custom-events.js
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/scss/components/_km-message-area.scss
- Help/Not Helpful
- added the core changes later we can change the design
-
-
-
- 
> TDH-1330 -: Help/Not Helpful

- .firebaserc
- .github/workflows/danger.yml
- firebase-deploy.sh
- firebase.json
- server/config/config-env.js
- deployment script for firebase. 
- NOTE: Project is currently selected by default. Ops team will create pipeline and pass project and firebase credentials dynamically. 
- https://widget-release.kommunicate.io/  Currently hosted on Firbase
-
-
- 
> OPS-785: deployment script for firebase

- webplugin/js/app/mck-sidebox-1.0.js
> remove the hard coded code

- cloudbuild.yaml
- firebase.json
-Have added rewrite and redirect in firebase.json 
-Also have improved cloudbuild.yaml file
-
-
-
- 
> Gcp ci firebase

- .firebaserc
- cloudbuild.yaml
- firebase.json
-I have added cloudbuild.yaml file for CI using cloud build (gcp) and have added firebase hosting configuration(firebase.json, .firebaserc)
-Motto to build CI Pipeline in gcp for chatwidget
- Rewrites and redirect wth status code added in firebase
-
-
-
- 
> Gcp cloud build firebase

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
> added new google api key

- webplugin/js/app/mck-sidebox-1.0.js
> Release conversation summary metadata check

- webplugin/js/app/kommunicate.js
- this is already a handled error 
changing console.error to console.debug
-
-
-
- 
> fixed Error fetching location  {} Cus-413

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
> TDH-1375 IN-release

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
> TDH-1375 EU Release 

- webplugin/js/app/mck-app.js
- webplugin/js/app/mck-sidebox-1.0.js
> TDH-1375 CN Release

- webplugin/css/app/km-sidebox.css
- webplugin/js/app/kommunicate-ui.js
- webplugin/js/app/kommunicate.custom.theme.js
- webplugin/js/app/labels/default-labels.js
- webplugin/js/app/mck-sidebox-1.0.js
- webplugin/template/mck-sidebox.html
In widget we keep most updated changes in development. Previously these changes were merged in master. Adding those changes in development branch
#1221
> Add business hour changes in development branch

- webplugin/js/app/mck-sidebox-1.0.js
> Cus 848 release

- webplugin/js/app/mck-sidebox-1.0.js
-  allowing  html code in text message
-
-
-
- 
>  allowing  html code in text message

- webplugin/js/app/mck-sidebox-1.0.js
- Transfer to an Offline Department: If a customer is moved to a department or a team that is OFFLINE or Outside of Business Hours, show the banner.
- Waiting During Away Hours: If a customer is waiting in a queue after business hours, show the banner. ( along with the Waiting Q message).
- Queue Transitions to Away Hours: If the queue was originally in business hours but switches to after-hours while the customer is still waiting, show the banner.
-
- Locally
- 
> Cus-926 Business hour improvements

- webplugin/js/app/mck-sidebox-1.0.js
- ref https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1330
-
-
-
- 
>  show unread count only for complete message not for the  each token
